/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsTestSendTestMessage } from "../../funcs/agentsTestSendTestMessage.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.TestMessage$inboundSchema,
};

export const tool$agentsTestSendTestMessage: ToolDefinition<typeof args> = {
  name: "agents-test-send-test-message",
  description: `Send New Message

Send a new message`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentsTestSendTestMessage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
