/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsAgentListActiveLabels } from "../../funcs/agentsAgentListActiveLabels.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$agentsAgentListActiveLabels: ToolDefinition = {
  name: "agents-agent-list-active-labels",
  description: `List Active Agent Labels

List all distinct labels in use across active agents.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await agentsAgentListActiveLabels(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
