/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsAgentGetAvailableSttProviders } from "../../funcs/agentsAgentGetAvailableSttProviders.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.AgentGetAvailableSttProvidersRequest$inboundSchema,
};

export const tool$agentsAgentGetAvailableSttProviders: ToolDefinition<
  typeof args
> = {
  name: "agents-agent-get-available-stt-providers",
  description: `Get Available Agent Stt Providers

Get the speech-to-text providers available to agents.

Each provider's \`status\` is resolved against the current date. Retired providers are omitted
unless they match \`selected_provider\`, so an agent still saved on a retired provider can render
it as a locked field.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentsAgentGetAvailableSttProviders(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
