/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { bridgePhrasesDelete } from "../../funcs/bridgePhrasesDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.BridgePhrasesDeleteRequest$inboundSchema,
};

export const tool$bridgePhrasesDelete: ToolDefinition<typeof args> = {
  name: "bridge-phrases-delete",
  description: `Delete Bridge Phrases

Delete a bridge phrases config.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await bridgePhrasesDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
