/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { channelsTwilioNumbersChannelsTwilioNumbersA2pComplianceCheck } from "../../funcs/channelsTwilioNumbersChannelsTwilioNumbersA2pComplianceCheck.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.ChannelsTwilioNumbersA2pComplianceCheckRequest$inboundSchema,
};

export const tool$channelsTwilioNumbersChannelsTwilioNumbersA2pComplianceCheck:
  ToolDefinition<typeof args> = {
    name:
      "channels-twilio-numbers-channels-twilio-numbers-a2p-compliance-check",
    description: `Verify Twilio Us A2P Compliance

Return whether Twilio shows this number on a US A2P messaging path with an approved brand.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await channelsTwilioNumbersChannelsTwilioNumbersA2pComplianceCheck(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
