/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customMessagesList } from "../../funcs/customMessagesList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CustomMessagesListRequest$inboundSchema,
};

export const tool$customMessagesList: ToolDefinition<typeof args> = {
  name: "custom-messages-list",
  description: `Custom Messages List

List the existing custom_messages`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customMessagesList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
