/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dashboardsPostGetDashboard } from "../../funcs/dashboardsPostGetDashboard.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostGetDashboardRequest$inboundSchema,
};

export const tool$dashboardsPostGetDashboard: ToolDefinition<typeof args> = {
  name: "dashboards-post-get-dashboard",
  description: `Post Fetch Info

METHOD: POST
URL: /dashboard/fetch_info
ARGUMENTS: None
RETURNS: Dashboard info for embedding`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await dashboardsPostGetDashboard(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
