/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dataSourcesUpdate } from "../../funcs/dataSourcesUpdate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.DataSourceUpdateRequest$inboundSchema,
};

export const tool$dataSourcesUpdate: ToolDefinition<typeof args> = {
  name: "data-sources-update",
  description: `Update Data Source

Update an existing data source.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await dataSourcesUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
