/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dataSourcesGetById } from "../../funcs/dataSourcesGetById.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DataSourcesGetByIdRequest$inboundSchema,
};

export const tool$dataSourcesGetById: ToolDefinition<typeof args> = {
  name: "data-sources-get-by-id",
  description: `Get Data Source

Fetch a given data source, including its text.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await dataSourcesGetById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
