/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { directoryDirectoryMemberHistory } from "../../funcs/directoryDirectoryMemberHistory.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DirectoryMemberHistoryRequest$inboundSchema,
};

export const tool$directoryDirectoryMemberHistory: ToolDefinition<typeof args> =
  {
    name: "directory-directory-member-history",
    description: `Get Directory Member History

Get version history for a directory member (contact).
Version 1 is always the oldest; order_by_direction only controls response order.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await directoryDirectoryMemberHistory(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
