/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { directoryList } from "../../funcs/directoryList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DirectoryMemberListRequest$inboundSchema,
};

export const tool$directoryList: ToolDefinition<typeof args> = {
  name: "directory-list",
  description: `Directory Member List

List the existing directory_members`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await directoryList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
