/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { directoryUpdate } from "../../funcs/directoryUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DirectoryMemberUpdateRequest$inboundSchema,
};

export const tool$directoryUpdate: ToolDefinition<typeof args> = {
  name: "directory-update",
  description: `Update Directory Member

Update a DirectoryMember.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await directoryUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
