/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { experimentsGetById } from "../../funcs/experimentsGetById.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ExperimentsGetByIdRequest$inboundSchema,
};

export const tool$experimentsGetById: ToolDefinition<typeof args> = {
  name: "experiments-get-by-id",
  description: `Get Experiment By Id

Get an experiment by its ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await experimentsGetById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
