/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { experimentsDelete } from "../../funcs/experimentsDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ExperimentsDeleteRequest$inboundSchema,
};

export const tool$experimentsDelete: ToolDefinition<typeof args> = {
  name: "experiments-delete",
  description: `Delete Experiment

Delete a (non-running) experiment.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await experimentsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
