/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentsList } from "../../funcs/incidentsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.IncidentListRequest$inboundSchema,
};

export const tool$incidentsList: ToolDefinition<typeof args> = {
  name: "incidents-list",
  description: `List Incidents

List service incidents with pagination and filtering`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await incidentsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
