/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { insightsList } from "../../funcs/insightsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.InsightsListRequest$inboundSchema,
};

export const tool$insightsList: ToolDefinition<typeof args> = {
  name: "insights-list",
  description: `Insights List

List the evaluated insights for sessions.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await insightsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
