/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { insightsWorkflowsListSessions } from "../../funcs/insightsWorkflowsListSessions.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.InsightsWorkflowSessionsRequest$inboundSchema,
};

export const tool$insightsWorkflowsListSessions: ToolDefinition<typeof args> = {
  name: "insights-workflows-list-sessions",
  description: `List Insight Workflow Sessions

List the sessions under a workflow, one row per session, with each tool's
results grouped into a \`\`results\`\` dict keyed by tool name.

Sessions come from the workflow's execution queue, so pending, processing and
failed sessions show up too, not just completed ones. A session that was
queued more than once appears only once. Insights reused from another
workflow still show up here.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await insightsWorkflowsListSessions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
