/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { insightsToolsCreate } from "../../funcs/insightsToolsCreate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.InsightToolInput$inboundSchema,
};

export const tool$insightsToolsCreate: ToolDefinition<typeof args> = {
  name: "insights-tools-create",
  description: `Create Insight Tool Configuration

Create a new insight tool.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await insightsToolsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
