/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { languageGroupsUpdate } from "../../funcs/languageGroupsUpdate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.LanguageGroupUpdateRequest$inboundSchema,
};

export const tool$languageGroupsUpdate: ToolDefinition<typeof args> = {
  name: "language-groups-update",
  description: `Update Language Group

Deprecated alias for \`PUT /api/v1/voice_groups/\`.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await languageGroupsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
