/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { outboundBatchesRemove } from "../../funcs/outboundBatchesRemove.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.OutboundBatchRemoveRequest$inboundSchema,
};

export const tool$outboundBatchesRemove: ToolDefinition<typeof args> = {
  name: "outbound-batches-remove",
  description: `Delete Requests By List Of Reference Ids`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await outboundBatchesRemove(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
