/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { promptsPromptsHistory } from "../../funcs/promptsPromptsHistory.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PromptsHistoryRequest$inboundSchema,
};

export const tool$promptsPromptsHistory: ToolDefinition<typeof args> = {
  name: "prompts-prompts-history",
  description: `Get Prompt History

Get a prompt by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await promptsPromptsHistory(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
