/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { promptsPromptGetSupportedLlms } from "../../funcs/promptsPromptGetSupportedLlms.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$promptsPromptGetSupportedLlms: ToolDefinition = {
  name: "prompts-prompt-get-supported-llms",
  description: `Get Supported Llm Configs

Get supported LLM configs.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await promptsPromptGetSupportedLlms(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
