/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pronunciationsPronunciationsUploadCsv } from "../../funcs/pronunciationsPronunciationsUploadCsv.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.BodyPronunciationsUploadCsv$inboundSchema,
};

export const tool$pronunciationsPronunciationsUploadCsv: ToolDefinition<
  typeof args
> = {
  name: "pronunciations-pronunciations-upload-csv",
  description: `Upload Pronunciations Csv`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await pronunciationsPronunciationsUploadCsv(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
