/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionsTranscriptGetById } from "../../funcs/sessionsTranscriptGetById.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SessionTranscriptGetByIdRequest$inboundSchema,
};

export const tool$sessionsTranscriptGetById: ToolDefinition<typeof args> = {
  name: "sessions-transcript-get-by-id",
  description: `Get Session Transcript By Id`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sessionsTranscriptGetById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
