/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionDebugGetSessionDataBySid } from "../../funcs/sessionDebugGetSessionDataBySid.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetSessionDataBySidRequest$inboundSchema,
};

export const tool$sessionDebugGetSessionDataBySid: ToolDefinition<typeof args> =
  {
    name: "session-debug-get-session-data-by-sid",
    description: `Get Session Data By Sid`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await sessionDebugGetSessionDataBySid(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
