/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { takeoutsTakeoutsGetFile } from "../../funcs/takeoutsTakeoutsGetFile.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.TakeoutsGetFileRequest$inboundSchema,
};

export const tool$takeoutsTakeoutsGetFile: ToolDefinition<typeof args> = {
  name: "takeouts-takeouts-get-file",
  description: `Get File`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await takeoutsTakeoutsGetFile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
