/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersUsersSendEmail } from "../../funcs/usersUsersSendEmail.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UsersSendEmailRequest$inboundSchema,
};

export const tool$usersUsersSendEmail: ToolDefinition<typeof args> = {
  name: "users-users-send-email",
  description: `Send User Email

Send a welcome email to a user.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersUsersSendEmail(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
