/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceGroupsUpdate } from "../../funcs/voiceGroupsUpdate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.VoiceGroupUpdateRequest$inboundSchema,
};

export const tool$voiceGroupsUpdate: ToolDefinition<typeof args> = {
  name: "voice-groups-update",
  description: `Update Voice Group

Update an existing voice group`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await voiceGroupsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
