/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceGroupsDelete } from "../../funcs/voiceGroupsDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.VoiceGroupsDeleteRequest$inboundSchema,
};

export const tool$voiceGroupsDelete: ToolDefinition<typeof args> = {
  name: "voice-groups-delete",
  description: `Delete Voice Group

Delete a voice group.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await voiceGroupsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
