/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { outboundCampaignsOutboundCampaignEdit } from "../funcs/outboundCampaignsOutboundCampaignEdit.js";
import { outboundCampaignsOutboundCampaignFetchAll } from "../funcs/outboundCampaignsOutboundCampaignFetchAll.js";
import { outboundCampaignsOutboundCampaignFetchOne } from "../funcs/outboundCampaignsOutboundCampaignFetchOne.js";
import { outboundCampaignsOutboundCampaignNew } from "../funcs/outboundCampaignsOutboundCampaignNew.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Campaigns extends ClientSDK {
  /**
   * List Outbound Communication Campaigns
   */
  async outboundCampaignFetchAll(
    request: operations.OutboundCampaignFetchAllRequest,
    options?: RequestOptions,
  ): Promise<Array<components.OutboundCampaign>> {
    return unwrapAsync(outboundCampaignsOutboundCampaignFetchAll(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Outbound Communication Campaign
   */
  async outboundCampaignNew(
    request: components.OutboundCampaignInput,
    options?: RequestOptions,
  ): Promise<components.OutboundCampaign> {
    return unwrapAsync(outboundCampaignsOutboundCampaignNew(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Outbound Communication Campaign
   */
  async outboundCampaignFetchOne(
    request: operations.OutboundCampaignFetchOneRequest,
    options?: RequestOptions,
  ): Promise<components.OutboundCampaign> {
    return unwrapAsync(outboundCampaignsOutboundCampaignFetchOne(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Outbound Communication Campaign
   */
  async outboundCampaignEdit(
    request: operations.OutboundCampaignEditRequest,
    options?: RequestOptions,
  ): Promise<components.OutboundCampaign> {
    return unwrapAsync(outboundCampaignsOutboundCampaignEdit(
      this,
      request,
      options,
    ));
  }
}
