/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsChatsChatsSendMessage } from "../funcs/agentsChatsChatsSendMessage.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Chats extends ClientSDK {
  /**
   * Send New Message
   *
   * @remarks
   * Send a new message
   */
  async chatsSendMessage(
    request: components.ChatMessage,
    options?: RequestOptions,
  ): Promise<components.ChatMessageResponse> {
    return unwrapAsync(agentsChatsChatsSendMessage(
      this,
      request,
      options,
    ));
  }
}
