/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pronunciationsPronunciationsUploadCsv } from "../funcs/pronunciationsPronunciationsUploadCsv.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Pronunciations extends ClientSDK {
  /**
   * Upload Pronunciations Csv
   */
  async pronunciationsUploadCsv(
    request: components.BodyPronunciationsUploadCsv,
    options?: RequestOptions,
  ): Promise<components.PronunciationsCsvUploadResponse> {
    return unwrapAsync(pronunciationsPronunciationsUploadCsv(
      this,
      request,
      options,
    ));
  }
}
