/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionsGenerateSessionRecordingUrls } from "../funcs/sessionsGenerateSessionRecordingUrls.js";
import { sessionsGetById } from "../funcs/sessionsGetById.js";
import { sessionsList } from "../funcs/sessionsList.js";
import { sessionsSessionRecordingStream } from "../funcs/sessionsSessionRecordingStream.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { Transcript } from "./transcript.js";

export class Sessions extends ClientSDK {
  private _transcript?: Transcript;
  get transcript(): Transcript {
    return (this._transcript ??= new Transcript(this._options));
  }

  /**
   * Sessions List
   */
  async list(
    request: operations.SessionsListRequest,
    options?: RequestOptions,
  ): Promise<components.ListResponseSession> {
    return unwrapAsync(sessionsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get A Single Session By Id
   */
  async getById(
    request: operations.SessionGetByIdRequest,
    options?: RequestOptions,
  ): Promise<components.Session> {
    return unwrapAsync(sessionsGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * Generate Recording Urls
   */
  async generateSessionRecordingUrls(
    request: operations.GenerateSessionRecordingUrlsRequest,
    options?: RequestOptions,
  ): Promise<components.SessionRecordingResponse> {
    return unwrapAsync(sessionsGenerateSessionRecordingUrls(
      this,
      request,
      options,
    ));
  }

  /**
   * Stream Recording
   */
  async sessionRecordingStream(
    request: operations.SessionRecordingStreamRequest,
    options?: RequestOptions,
  ): Promise<ReadableStream<Uint8Array>> {
    return unwrapAsync(sessionsSessionRecordingStream(
      this,
      request,
      options,
    ));
  }
}
