/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { takeoutsCreateTakeoutApiV1TakeoutsCreatePost } from "../funcs/takeoutsCreateTakeoutApiV1TakeoutsCreatePost.js";
import { takeoutsGetTakeoutApiV1TakeoutsGetJobIdGet } from "../funcs/takeoutsGetTakeoutApiV1TakeoutsGetJobIdGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Takeouts extends ClientSDK {
  /**
   * Create Takeout
   */
  async createTakeoutApiV1TakeoutsCreatePost(
    options?: RequestOptions,
  ): Promise<components.CreateTakeoutResponse> {
    return unwrapAsync(takeoutsCreateTakeoutApiV1TakeoutsCreatePost(
      this,
      options,
    ));
  }

  /**
   * Get Takeout
   */
  async getTakeoutApiV1TakeoutsGetJobIdGet(
    request: operations.GetTakeoutApiV1TakeoutsGetJobIdGetRequest,
    options?: RequestOptions,
  ): Promise<components.TakeoutStatusResponse> {
    return unwrapAsync(takeoutsGetTakeoutApiV1TakeoutsGetJobIdGet(
      this,
      request,
      options,
    ));
  }
}
