/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionsTimelineGetById } from "../funcs/sessionsTimelineGetById.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Timeline extends ClientSDK {
  /**
   * Get Session Timeline By Id
   *
   * @remarks
   * Consolidated, time-ordered timeline of a session's events.
   */
  async getById(
    request: operations.SessionTimelineGetByIdRequest,
    options?: RequestOptions,
  ): Promise<components.SessionTimelineResponse> {
    return unwrapAsync(sessionsTimelineGetById(
      this,
      request,
      options,
    ));
  }
}
