/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { v1PostSessionEventsDashboard } from "../funcs/v1PostSessionEventsDashboard.js";
import { v1PostSessionsDashboard } from "../funcs/v1PostSessionsDashboard.js";
import { v1PostSessionSummaryDashboard } from "../funcs/v1PostSessionSummaryDashboard.js";
import { v1PostSessionTransfersDashboard } from "../funcs/v1PostSessionTransfersDashboard.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class V1 extends ClientSDK {
  /**
   * Post Session Events
   *
   * @remarks
   * METHOD: POST
   * URL: /dashboard/session_events
   * ARGUMENTS: None
   * RETURNS: Dashboard info for embedding
   */
  async postSessionEventsDashboard(
    options?: RequestOptions,
  ): Promise<components.Dashboard> {
    return unwrapAsync(v1PostSessionEventsDashboard(
      this,
      options,
    ));
  }

  /**
   * Post Session Summary
   *
   * @remarks
   * METHOD: POST
   * URL: /dashboard/session_summary
   * ARGUMENTS: None
   * RETURNS: Dashboard info for embedding
   */
  async postSessionSummaryDashboard(
    options?: RequestOptions,
  ): Promise<components.Dashboard> {
    return unwrapAsync(v1PostSessionSummaryDashboard(
      this,
      options,
    ));
  }

  /**
   * Post Session Transfers
   *
   * @remarks
   * METHOD: POST
   * URL: /dashboard/session_transfers
   * ARGUMENTS: None
   * RETURNS: Dashboard info for embedding
   */
  async postSessionTransfersDashboard(
    options?: RequestOptions,
  ): Promise<components.Dashboard> {
    return unwrapAsync(v1PostSessionTransfersDashboard(
      this,
      options,
    ));
  }

  /**
   * Post Sessions
   *
   * @remarks
   * METHOD: POST
   * URL: /dashboard/sessions
   * ARGUMENTS: None
   * RETURNS: Dashboard info for embedding
   */
  async postSessionsDashboard(
    options?: RequestOptions,
  ): Promise<components.Dashboard> {
    return unwrapAsync(v1PostSessionsDashboard(
      this,
      options,
    ));
  }
}
