workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    SyllableSDK-OAS:
        inputs:
            - location: ./openapi.json
        overlays:
            - location: ./overlay-remove-V1.yaml
            - location: ./codeSamples.yaml
        output: openapi.yaml
targets:
    syllable-sdk:
        target: typescript
        source: SyllableSDK-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
            output: codeSamples.yaml
