workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    SyllableSDK-OAS:
        inputs:
            - location: ./openapi.json
        overlays:
            - location: ./overlay-remove-V1.yaml
        output: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/syllable/syllable/syllable-sdk-oas
targets:
    syllable-sdk:
        target: typescript
        source: SyllableSDK-OAS
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/syllable/syllable/code-samples-typescript-sdk-syllable-sdk-oas
            labelOverride:
                fixedValue: Typescript (SDK)
