workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    SyllableSDK-OAS:
        inputs:
            - location: ./openapi.json
        overlays:
            - location: ./overlay-remove-V1.yaml
        output: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/actiumhealth/actiumhealth/syllable-sdk-oas
targets:
    syllable-sdk:
        target: typescript
        source: SyllableSDK-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/actiumhealth/actiumhealth/syllable-sdk-oas-code-samples
