workflowVersion: 1.0.0
speakeasyVersion: 1.493.2
sources:
    SyllableSDK-OAS:
        inputs:
            - location: ./openapi.json
        overlays:
            - location: ./overlay-remove-V1.yaml
        output: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/syllable/syllable/syllable-sdk-oas
targets:
    syllable-sdk:
        target: typescript
        source: SyllableSDK-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/syllable/syllable/syllable-typescript-sdk-oas-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
