/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type ChannelTargetsDeleteRequest = {
  channelId: string;
  targetId: string;
};

/** @internal */
export const ChannelTargetsDeleteRequest$inboundSchema: z.ZodType<
  ChannelTargetsDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  target_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "target_id": "targetId",
  });
});

/** @internal */
export type ChannelTargetsDeleteRequest$Outbound = {
  channel_id: string;
  target_id: string;
};

/** @internal */
export const ChannelTargetsDeleteRequest$outboundSchema: z.ZodType<
  ChannelTargetsDeleteRequest$Outbound,
  z.ZodTypeDef,
  ChannelTargetsDeleteRequest
> = z.object({
  channelId: z.string(),
  targetId: z.string(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    targetId: "target_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChannelTargetsDeleteRequest$ {
  /** @deprecated use `ChannelTargetsDeleteRequest$inboundSchema` instead. */
  export const inboundSchema = ChannelTargetsDeleteRequest$inboundSchema;
  /** @deprecated use `ChannelTargetsDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = ChannelTargetsDeleteRequest$outboundSchema;
  /** @deprecated use `ChannelTargetsDeleteRequest$Outbound` instead. */
  export type Outbound = ChannelTargetsDeleteRequest$Outbound;
}
