/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type ChannelsTargetUpdateRequest = {
  channelId: number;
  targetId: number;
  channelTarget: components.ChannelTarget;
};

/** @internal */
export const ChannelsTargetUpdateRequest$inboundSchema: z.ZodType<
  ChannelsTargetUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.number().int(),
  target_id: z.number().int(),
  ChannelTarget: components.ChannelTarget$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "target_id": "targetId",
    "ChannelTarget": "channelTarget",
  });
});

/** @internal */
export type ChannelsTargetUpdateRequest$Outbound = {
  channel_id: number;
  target_id: number;
  ChannelTarget: components.ChannelTarget$Outbound;
};

/** @internal */
export const ChannelsTargetUpdateRequest$outboundSchema: z.ZodType<
  ChannelsTargetUpdateRequest$Outbound,
  z.ZodTypeDef,
  ChannelsTargetUpdateRequest
> = z.object({
  channelId: z.number().int(),
  targetId: z.number().int(),
  channelTarget: components.ChannelTarget$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    targetId: "target_id",
    channelTarget: "ChannelTarget",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChannelsTargetUpdateRequest$ {
  /** @deprecated use `ChannelsTargetUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = ChannelsTargetUpdateRequest$inboundSchema;
  /** @deprecated use `ChannelsTargetUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = ChannelsTargetUpdateRequest$outboundSchema;
  /** @deprecated use `ChannelsTargetUpdateRequest$Outbound` instead. */
  export type Outbound = ChannelsTargetUpdateRequest$Outbound;
}
