/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CustomMessageGetByIdRequest = {
  customMessageId: number;
};

/** @internal */
export const CustomMessageGetByIdRequest$inboundSchema: z.ZodType<
  CustomMessageGetByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  custom_message_id: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "custom_message_id": "customMessageId",
  });
});
/** @internal */
export type CustomMessageGetByIdRequest$Outbound = {
  custom_message_id: number;
};

/** @internal */
export const CustomMessageGetByIdRequest$outboundSchema: z.ZodType<
  CustomMessageGetByIdRequest$Outbound,
  z.ZodTypeDef,
  CustomMessageGetByIdRequest
> = z.object({
  customMessageId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    customMessageId: "custom_message_id",
  });
});

export function customMessageGetByIdRequestToJSON(
  customMessageGetByIdRequest: CustomMessageGetByIdRequest,
): string {
  return JSON.stringify(
    CustomMessageGetByIdRequest$outboundSchema.parse(
      customMessageGetByIdRequest,
    ),
  );
}
export function customMessageGetByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<CustomMessageGetByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomMessageGetByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomMessageGetByIdRequest' from JSON`,
  );
}
