/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CustomMessagesListRequest = {
  page?: number | null | undefined;
  limit?: number | undefined;
  searchFields?: Array<components.CustomMessageProperties> | undefined;
  searchFieldValues?: Array<string> | undefined;
  orderBy?: components.CustomMessageProperties | null | undefined;
  orderByDirection?: components.OrderByDirection | null | undefined;
  fields?: Array<components.CustomMessageProperties> | null | undefined;
  startDatetime?: string | null | undefined;
  endDatetime?: string | null | undefined;
};

/** @internal */
export const CustomMessagesListRequest$inboundSchema: z.ZodType<
  CustomMessagesListRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.nullable(z.number().int()).optional(),
  limit: z.number().int().default(25),
  search_fields: z.array(components.CustomMessageProperties$inboundSchema)
    .optional(),
  search_field_values: z.array(z.string()).optional(),
  order_by: z.nullable(components.CustomMessageProperties$inboundSchema)
    .optional(),
  order_by_direction: z.nullable(components.OrderByDirection$inboundSchema)
    .optional(),
  fields: z.nullable(z.array(components.CustomMessageProperties$inboundSchema))
    .optional(),
  start_datetime: z.nullable(z.string()).optional(),
  end_datetime: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "search_fields": "searchFields",
    "search_field_values": "searchFieldValues",
    "order_by": "orderBy",
    "order_by_direction": "orderByDirection",
    "start_datetime": "startDatetime",
    "end_datetime": "endDatetime",
  });
});

/** @internal */
export type CustomMessagesListRequest$Outbound = {
  page?: number | null | undefined;
  limit: number;
  search_fields?: Array<string> | undefined;
  search_field_values?: Array<string> | undefined;
  order_by?: string | null | undefined;
  order_by_direction?: string | null | undefined;
  fields?: Array<string> | null | undefined;
  start_datetime?: string | null | undefined;
  end_datetime?: string | null | undefined;
};

/** @internal */
export const CustomMessagesListRequest$outboundSchema: z.ZodType<
  CustomMessagesListRequest$Outbound,
  z.ZodTypeDef,
  CustomMessagesListRequest
> = z.object({
  page: z.nullable(z.number().int()).optional(),
  limit: z.number().int().default(25),
  searchFields: z.array(components.CustomMessageProperties$outboundSchema)
    .optional(),
  searchFieldValues: z.array(z.string()).optional(),
  orderBy: z.nullable(components.CustomMessageProperties$outboundSchema)
    .optional(),
  orderByDirection: z.nullable(components.OrderByDirection$outboundSchema)
    .optional(),
  fields: z.nullable(z.array(components.CustomMessageProperties$outboundSchema))
    .optional(),
  startDatetime: z.nullable(z.string()).optional(),
  endDatetime: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    searchFields: "search_fields",
    searchFieldValues: "search_field_values",
    orderBy: "order_by",
    orderByDirection: "order_by_direction",
    startDatetime: "start_datetime",
    endDatetime: "end_datetime",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomMessagesListRequest$ {
  /** @deprecated use `CustomMessagesListRequest$inboundSchema` instead. */
  export const inboundSchema = CustomMessagesListRequest$inboundSchema;
  /** @deprecated use `CustomMessagesListRequest$outboundSchema` instead. */
  export const outboundSchema = CustomMessagesListRequest$outboundSchema;
  /** @deprecated use `CustomMessagesListRequest$Outbound` instead. */
  export type Outbound = CustomMessagesListRequest$Outbound;
}

export function customMessagesListRequestToJSON(
  customMessagesListRequest: CustomMessagesListRequest,
): string {
  return JSON.stringify(
    CustomMessagesListRequest$outboundSchema.parse(customMessagesListRequest),
  );
}

export function customMessagesListRequestFromJSON(
  jsonString: string,
): SafeParseResult<CustomMessagesListRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomMessagesListRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomMessagesListRequest' from JSON`,
  );
}
