/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DirectoryMemberHistoryRequest = {
  memberId: number;
  /**
   * Page number (0-based)
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
};

/** @internal */
export const DirectoryMemberHistoryRequest$inboundSchema: z.ZodType<
  DirectoryMemberHistoryRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  member_id: z.number().int(),
  page: z.number().int().default(0),
  limit: z.number().int().default(25),
}).transform((v) => {
  return remap$(v, {
    "member_id": "memberId",
  });
});
/** @internal */
export type DirectoryMemberHistoryRequest$Outbound = {
  member_id: number;
  page: number;
  limit: number;
};

/** @internal */
export const DirectoryMemberHistoryRequest$outboundSchema: z.ZodType<
  DirectoryMemberHistoryRequest$Outbound,
  z.ZodTypeDef,
  DirectoryMemberHistoryRequest
> = z.object({
  memberId: z.number().int(),
  page: z.number().int().default(0),
  limit: z.number().int().default(25),
}).transform((v) => {
  return remap$(v, {
    memberId: "member_id",
  });
});

export function directoryMemberHistoryRequestToJSON(
  directoryMemberHistoryRequest: DirectoryMemberHistoryRequest,
): string {
  return JSON.stringify(
    DirectoryMemberHistoryRequest$outboundSchema.parse(
      directoryMemberHistoryRequest,
    ),
  );
}
export function directoryMemberHistoryRequestFromJSON(
  jsonString: string,
): SafeParseResult<DirectoryMemberHistoryRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DirectoryMemberHistoryRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DirectoryMemberHistoryRequest' from JSON`,
  );
}
