/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ExperimentsGetByIdRequest = {
  experimentId: number;
};

/** @internal */
export const ExperimentsGetByIdRequest$inboundSchema: z.ZodType<
  ExperimentsGetByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  experiment_id: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "experiment_id": "experimentId",
  });
});
/** @internal */
export type ExperimentsGetByIdRequest$Outbound = {
  experiment_id: number;
};

/** @internal */
export const ExperimentsGetByIdRequest$outboundSchema: z.ZodType<
  ExperimentsGetByIdRequest$Outbound,
  z.ZodTypeDef,
  ExperimentsGetByIdRequest
> = z.object({
  experimentId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    experimentId: "experiment_id",
  });
});

export function experimentsGetByIdRequestToJSON(
  experimentsGetByIdRequest: ExperimentsGetByIdRequest,
): string {
  return JSON.stringify(
    ExperimentsGetByIdRequest$outboundSchema.parse(experimentsGetByIdRequest),
  );
}
export function experimentsGetByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<ExperimentsGetByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExperimentsGetByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExperimentsGetByIdRequest' from JSON`,
  );
}
