/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InsightToolGetByIdRequest = {
  toolId: string;
};

/** @internal */
export const InsightToolGetByIdRequest$inboundSchema: z.ZodType<
  InsightToolGetByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  tool_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "tool_id": "toolId",
  });
});

/** @internal */
export type InsightToolGetByIdRequest$Outbound = {
  tool_id: string;
};

/** @internal */
export const InsightToolGetByIdRequest$outboundSchema: z.ZodType<
  InsightToolGetByIdRequest$Outbound,
  z.ZodTypeDef,
  InsightToolGetByIdRequest
> = z.object({
  toolId: z.string(),
}).transform((v) => {
  return remap$(v, {
    toolId: "tool_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InsightToolGetByIdRequest$ {
  /** @deprecated use `InsightToolGetByIdRequest$inboundSchema` instead. */
  export const inboundSchema = InsightToolGetByIdRequest$inboundSchema;
  /** @deprecated use `InsightToolGetByIdRequest$outboundSchema` instead. */
  export const outboundSchema = InsightToolGetByIdRequest$outboundSchema;
  /** @deprecated use `InsightToolGetByIdRequest$Outbound` instead. */
  export type Outbound = InsightToolGetByIdRequest$Outbound;
}

export function insightToolGetByIdRequestToJSON(
  insightToolGetByIdRequest: InsightToolGetByIdRequest,
): string {
  return JSON.stringify(
    InsightToolGetByIdRequest$outboundSchema.parse(insightToolGetByIdRequest),
  );
}

export function insightToolGetByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<InsightToolGetByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InsightToolGetByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InsightToolGetByIdRequest' from JSON`,
  );
}
