/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LanguageGroupsGetByIdRequest = {
  languageGroupId: number;
};

/** @internal */
export const LanguageGroupsGetByIdRequest$inboundSchema: z.ZodType<
  LanguageGroupsGetByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  language_group_id: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "language_group_id": "languageGroupId",
  });
});

/** @internal */
export type LanguageGroupsGetByIdRequest$Outbound = {
  language_group_id: number;
};

/** @internal */
export const LanguageGroupsGetByIdRequest$outboundSchema: z.ZodType<
  LanguageGroupsGetByIdRequest$Outbound,
  z.ZodTypeDef,
  LanguageGroupsGetByIdRequest
> = z.object({
  languageGroupId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    languageGroupId: "language_group_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LanguageGroupsGetByIdRequest$ {
  /** @deprecated use `LanguageGroupsGetByIdRequest$inboundSchema` instead. */
  export const inboundSchema = LanguageGroupsGetByIdRequest$inboundSchema;
  /** @deprecated use `LanguageGroupsGetByIdRequest$outboundSchema` instead. */
  export const outboundSchema = LanguageGroupsGetByIdRequest$outboundSchema;
  /** @deprecated use `LanguageGroupsGetByIdRequest$Outbound` instead. */
  export type Outbound = LanguageGroupsGetByIdRequest$Outbound;
}

export function languageGroupsGetByIdRequestToJSON(
  languageGroupsGetByIdRequest: LanguageGroupsGetByIdRequest,
): string {
  return JSON.stringify(
    LanguageGroupsGetByIdRequest$outboundSchema.parse(
      languageGroupsGetByIdRequest,
    ),
  );
}

export function languageGroupsGetByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<LanguageGroupsGetByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LanguageGroupsGetByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LanguageGroupsGetByIdRequest' from JSON`,
  );
}
