/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PromptsListQueryParamOrderBy = {
  Id: "id",
  Name: "name",
  Context: "context",
  Tools: "tools",
  LlmConfig: "llm_config",
} as const;
export type PromptsListQueryParamOrderBy = ClosedEnum<
  typeof PromptsListQueryParamOrderBy
>;

export const PromptsListQueryParamOrderByDirection = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type PromptsListQueryParamOrderByDirection = ClosedEnum<
  typeof PromptsListQueryParamOrderByDirection
>;

export type PromptsListRequest = {
  page?: number | null | undefined;
  limit?: number | undefined;
  searchFields?: Array<components.PromptProperties> | undefined;
  searchFieldValues?: Array<string> | undefined;
  orderBy?: PromptsListQueryParamOrderBy | undefined;
  orderByDirection?: PromptsListQueryParamOrderByDirection | undefined;
  fields?: Array<components.PromptProperties> | null | undefined;
  startDatetime?: string | null | undefined;
  endDatetime?: string | null | undefined;
};

/** @internal */
export const PromptsListQueryParamOrderBy$inboundSchema: z.ZodNativeEnum<
  typeof PromptsListQueryParamOrderBy
> = z.nativeEnum(PromptsListQueryParamOrderBy);

/** @internal */
export const PromptsListQueryParamOrderBy$outboundSchema: z.ZodNativeEnum<
  typeof PromptsListQueryParamOrderBy
> = PromptsListQueryParamOrderBy$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PromptsListQueryParamOrderBy$ {
  /** @deprecated use `PromptsListQueryParamOrderBy$inboundSchema` instead. */
  export const inboundSchema = PromptsListQueryParamOrderBy$inboundSchema;
  /** @deprecated use `PromptsListQueryParamOrderBy$outboundSchema` instead. */
  export const outboundSchema = PromptsListQueryParamOrderBy$outboundSchema;
}

/** @internal */
export const PromptsListQueryParamOrderByDirection$inboundSchema:
  z.ZodNativeEnum<typeof PromptsListQueryParamOrderByDirection> = z.nativeEnum(
    PromptsListQueryParamOrderByDirection,
  );

/** @internal */
export const PromptsListQueryParamOrderByDirection$outboundSchema:
  z.ZodNativeEnum<typeof PromptsListQueryParamOrderByDirection> =
    PromptsListQueryParamOrderByDirection$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PromptsListQueryParamOrderByDirection$ {
  /** @deprecated use `PromptsListQueryParamOrderByDirection$inboundSchema` instead. */
  export const inboundSchema =
    PromptsListQueryParamOrderByDirection$inboundSchema;
  /** @deprecated use `PromptsListQueryParamOrderByDirection$outboundSchema` instead. */
  export const outboundSchema =
    PromptsListQueryParamOrderByDirection$outboundSchema;
}

/** @internal */
export const PromptsListRequest$inboundSchema: z.ZodType<
  PromptsListRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.nullable(z.number().int()).optional(),
  limit: z.number().int().default(25),
  search_fields: z.array(components.PromptProperties$inboundSchema).optional(),
  search_field_values: z.array(z.string()).optional(),
  order_by: PromptsListQueryParamOrderBy$inboundSchema.optional(),
  order_by_direction: PromptsListQueryParamOrderByDirection$inboundSchema
    .optional(),
  fields: z.nullable(z.array(components.PromptProperties$inboundSchema))
    .optional(),
  start_datetime: z.nullable(z.string()).optional(),
  end_datetime: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "search_fields": "searchFields",
    "search_field_values": "searchFieldValues",
    "order_by": "orderBy",
    "order_by_direction": "orderByDirection",
    "start_datetime": "startDatetime",
    "end_datetime": "endDatetime",
  });
});

/** @internal */
export type PromptsListRequest$Outbound = {
  page?: number | null | undefined;
  limit: number;
  search_fields?: Array<string> | undefined;
  search_field_values?: Array<string> | undefined;
  order_by?: string | undefined;
  order_by_direction?: string | undefined;
  fields?: Array<string> | null | undefined;
  start_datetime?: string | null | undefined;
  end_datetime?: string | null | undefined;
};

/** @internal */
export const PromptsListRequest$outboundSchema: z.ZodType<
  PromptsListRequest$Outbound,
  z.ZodTypeDef,
  PromptsListRequest
> = z.object({
  page: z.nullable(z.number().int()).optional(),
  limit: z.number().int().default(25),
  searchFields: z.array(components.PromptProperties$outboundSchema).optional(),
  searchFieldValues: z.array(z.string()).optional(),
  orderBy: PromptsListQueryParamOrderBy$outboundSchema.optional(),
  orderByDirection: PromptsListQueryParamOrderByDirection$outboundSchema
    .optional(),
  fields: z.nullable(z.array(components.PromptProperties$outboundSchema))
    .optional(),
  startDatetime: z.nullable(z.string()).optional(),
  endDatetime: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    searchFields: "search_fields",
    searchFieldValues: "search_field_values",
    orderBy: "order_by",
    orderByDirection: "order_by_direction",
    startDatetime: "start_datetime",
    endDatetime: "end_datetime",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PromptsListRequest$ {
  /** @deprecated use `PromptsListRequest$inboundSchema` instead. */
  export const inboundSchema = PromptsListRequest$inboundSchema;
  /** @deprecated use `PromptsListRequest$outboundSchema` instead. */
  export const outboundSchema = PromptsListRequest$outboundSchema;
  /** @deprecated use `PromptsListRequest$Outbound` instead. */
  export type Outbound = PromptsListRequest$Outbound;
}

export function promptsListRequestToJSON(
  promptsListRequest: PromptsListRequest,
): string {
  return JSON.stringify(
    PromptsListRequest$outboundSchema.parse(promptsListRequest),
  );
}

export function promptsListRequestFromJSON(
  jsonString: string,
): SafeParseResult<PromptsListRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PromptsListRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PromptsListRequest' from JSON`,
  );
}
