/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PronunciationsDownloadCsvResponse = {
  headers: { [k: string]: Array<string> };
  result: ReadableStream<Uint8Array>;
};

/** @internal */
export const PronunciationsDownloadCsvResponse$inboundSchema: z.ZodType<
  PronunciationsDownloadCsvResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.instanceof(ReadableStream<Uint8Array>),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type PronunciationsDownloadCsvResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: ReadableStream<Uint8Array>;
};

/** @internal */
export const PronunciationsDownloadCsvResponse$outboundSchema: z.ZodType<
  PronunciationsDownloadCsvResponse$Outbound,
  z.ZodTypeDef,
  PronunciationsDownloadCsvResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.instanceof(ReadableStream<Uint8Array>),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PronunciationsDownloadCsvResponse$ {
  /** @deprecated use `PronunciationsDownloadCsvResponse$inboundSchema` instead. */
  export const inboundSchema = PronunciationsDownloadCsvResponse$inboundSchema;
  /** @deprecated use `PronunciationsDownloadCsvResponse$outboundSchema` instead. */
  export const outboundSchema =
    PronunciationsDownloadCsvResponse$outboundSchema;
  /** @deprecated use `PronunciationsDownloadCsvResponse$Outbound` instead. */
  export type Outbound = PronunciationsDownloadCsvResponse$Outbound;
}

export function pronunciationsDownloadCsvResponseToJSON(
  pronunciationsDownloadCsvResponse: PronunciationsDownloadCsvResponse,
): string {
  return JSON.stringify(
    PronunciationsDownloadCsvResponse$outboundSchema.parse(
      pronunciationsDownloadCsvResponse,
    ),
  );
}

export function pronunciationsDownloadCsvResponseFromJSON(
  jsonString: string,
): SafeParseResult<PronunciationsDownloadCsvResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PronunciationsDownloadCsvResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PronunciationsDownloadCsvResponse' from JSON`,
  );
}
