/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SessionRecordingStreamRequest = {
  token: string;
};

/** @internal */
export const SessionRecordingStreamRequest$inboundSchema: z.ZodType<
  SessionRecordingStreamRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: z.string(),
});
/** @internal */
export type SessionRecordingStreamRequest$Outbound = {
  token: string;
};

/** @internal */
export const SessionRecordingStreamRequest$outboundSchema: z.ZodType<
  SessionRecordingStreamRequest$Outbound,
  z.ZodTypeDef,
  SessionRecordingStreamRequest
> = z.object({
  token: z.string(),
});

export function sessionRecordingStreamRequestToJSON(
  sessionRecordingStreamRequest: SessionRecordingStreamRequest,
): string {
  return JSON.stringify(
    SessionRecordingStreamRequest$outboundSchema.parse(
      sessionRecordingStreamRequest,
    ),
  );
}
export function sessionRecordingStreamRequestFromJSON(
  jsonString: string,
): SafeParseResult<SessionRecordingStreamRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SessionRecordingStreamRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SessionRecordingStreamRequest' from JSON`,
  );
}
