/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Body to check US A2P / Messaging Service setup for one number on the Twilio channel.
 */
export type A2pMessagingPathCheckRequest = {
  /**
   * E.164 phone number exactly as Twilio stores it for this incoming number.
   */
  phone: string;
};

/** @internal */
export const A2pMessagingPathCheckRequest$inboundSchema: z.ZodType<
  A2pMessagingPathCheckRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  phone: z.string(),
});
/** @internal */
export type A2pMessagingPathCheckRequest$Outbound = {
  phone: string;
};

/** @internal */
export const A2pMessagingPathCheckRequest$outboundSchema: z.ZodType<
  A2pMessagingPathCheckRequest$Outbound,
  z.ZodTypeDef,
  A2pMessagingPathCheckRequest
> = z.object({
  phone: z.string(),
});

export function a2pMessagingPathCheckRequestToJSON(
  a2pMessagingPathCheckRequest: A2pMessagingPathCheckRequest,
): string {
  return JSON.stringify(
    A2pMessagingPathCheckRequest$outboundSchema.parse(
      a2pMessagingPathCheckRequest,
    ),
  );
}
export function a2pMessagingPathCheckRequestFromJSON(
  jsonString: string,
): SafeParseResult<A2pMessagingPathCheckRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => A2pMessagingPathCheckRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'A2pMessagingPathCheckRequest' from JSON`,
  );
}
