/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BridgePhrasesConfigPayload,
  BridgePhrasesConfigPayload$inboundSchema,
  BridgePhrasesConfigPayload$Outbound,
  BridgePhrasesConfigPayload$outboundSchema,
} from "./bridgephrasesconfigpayload.js";

/**
 * Request model to update an existing bridge phrases config.
 */
export type BridgePhrasesUpdateRequest = {
  /**
   * The name of the bridge phrases config.
   */
  name: string;
  /**
   * Description of the bridge phrases config.
   */
  description?: string | null | undefined;
  /**
   * The `config` JSONB payload stored on a bridge_phrases row.
   *
   * @remarks
   *
   * Holds the default phrases plus an inline list of per-tool overrides, each with
   * optional per-language (`localized`) overrides. Mirrors the shape documented in
   * docs/bridge-phrases-table-migration.md §5.2.
   */
  config?: BridgePhrasesConfigPayload | undefined;
  /**
   * Whether this config should be marked as the default for its suborg. Omit (null) to preserve the existing value; pass true/false to set or unset it. At most one non-deleted config per suborg may be the default; the API returns a 400 if a second default is requested while another is already set.
   */
  isDefault?: boolean | null | undefined;
  /**
   * The ID of the bridge phrases config to update.
   */
  id: number;
  /**
   * Comments for the most recent edit.
   */
  editComments?: string | null | undefined;
};

/** @internal */
export const BridgePhrasesUpdateRequest$inboundSchema: z.ZodType<
  BridgePhrasesUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  config: BridgePhrasesConfigPayload$inboundSchema.optional(),
  is_default: z.nullable(z.boolean()).optional(),
  id: z.number().int(),
  edit_comments: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "is_default": "isDefault",
    "edit_comments": "editComments",
  });
});
/** @internal */
export type BridgePhrasesUpdateRequest$Outbound = {
  name: string;
  description?: string | null | undefined;
  config?: BridgePhrasesConfigPayload$Outbound | undefined;
  is_default?: boolean | null | undefined;
  id: number;
  edit_comments?: string | null | undefined;
};

/** @internal */
export const BridgePhrasesUpdateRequest$outboundSchema: z.ZodType<
  BridgePhrasesUpdateRequest$Outbound,
  z.ZodTypeDef,
  BridgePhrasesUpdateRequest
> = z.object({
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  config: BridgePhrasesConfigPayload$outboundSchema.optional(),
  isDefault: z.nullable(z.boolean()).optional(),
  id: z.number().int(),
  editComments: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    isDefault: "is_default",
    editComments: "edit_comments",
  });
});

export function bridgePhrasesUpdateRequestToJSON(
  bridgePhrasesUpdateRequest: BridgePhrasesUpdateRequest,
): string {
  return JSON.stringify(
    BridgePhrasesUpdateRequest$outboundSchema.parse(bridgePhrasesUpdateRequest),
  );
}
export function bridgePhrasesUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<BridgePhrasesUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BridgePhrasesUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BridgePhrasesUpdateRequest' from JSON`,
  );
}
