/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessages,
  LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessages$inboundSchema,
  LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessages$Outbound,
  LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessages$outboundSchema,
} from "./libdatabasedaoorganizationbridgephrasesdaobridgephrasemessages.js";
import {
  ToolBridgePhraseConfig,
  ToolBridgePhraseConfig$inboundSchema,
  ToolBridgePhraseConfig$Outbound,
  ToolBridgePhraseConfig$outboundSchema,
} from "./toolbridgephraseconfig.js";

/**
 * The `config` JSONB payload stored on a bridge_phrases row.
 *
 * @remarks
 *
 * Holds the default phrases plus an inline list of per-tool overrides, each with
 * optional per-language (`localized`) overrides. Mirrors the shape documented in
 * docs/bridge-phrases-table-migration.md §5.2.
 */
export type BridgePhrasesConfigPayload = {
  /**
   * Bridge phrase messages for a single scope (default or one tool).
   */
  phrases?:
    | LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessages
    | undefined;
  /**
   * Per-tool phrase overrides.
   */
  tools?: Array<ToolBridgePhraseConfig> | undefined;
  /**
   * Seconds of caller silence before injecting the first bridge phrase. When unset, the service-wide default applies.
   */
  smartTurnTimeoutSeconds?: number | null | undefined;
  /**
   * Whether to randomize the order of bridge phrases. When true, the order of the bridge phrases is randomized for each call.
   */
  randomizeBridgePhrases?: boolean | undefined;
};

/** @internal */
export const BridgePhrasesConfigPayload$inboundSchema: z.ZodType<
  BridgePhrasesConfigPayload,
  z.ZodTypeDef,
  unknown
> = z.object({
  phrases:
    LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessages$inboundSchema
      .optional(),
  tools: z.array(ToolBridgePhraseConfig$inboundSchema).optional(),
  smart_turn_timeout_seconds: z.nullable(z.number()).optional(),
  randomize_bridge_phrases: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    "smart_turn_timeout_seconds": "smartTurnTimeoutSeconds",
    "randomize_bridge_phrases": "randomizeBridgePhrases",
  });
});
/** @internal */
export type BridgePhrasesConfigPayload$Outbound = {
  phrases?:
    | LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessages$Outbound
    | undefined;
  tools?: Array<ToolBridgePhraseConfig$Outbound> | undefined;
  smart_turn_timeout_seconds?: number | null | undefined;
  randomize_bridge_phrases: boolean;
};

/** @internal */
export const BridgePhrasesConfigPayload$outboundSchema: z.ZodType<
  BridgePhrasesConfigPayload$Outbound,
  z.ZodTypeDef,
  BridgePhrasesConfigPayload
> = z.object({
  phrases:
    LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessages$outboundSchema
      .optional(),
  tools: z.array(ToolBridgePhraseConfig$outboundSchema).optional(),
  smartTurnTimeoutSeconds: z.nullable(z.number()).optional(),
  randomizeBridgePhrases: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    smartTurnTimeoutSeconds: "smart_turn_timeout_seconds",
    randomizeBridgePhrases: "randomize_bridge_phrases",
  });
});

export function bridgePhrasesConfigPayloadToJSON(
  bridgePhrasesConfigPayload: BridgePhrasesConfigPayload,
): string {
  return JSON.stringify(
    BridgePhrasesConfigPayload$outboundSchema.parse(bridgePhrasesConfigPayload),
  );
}
export function bridgePhrasesConfigPayloadFromJSON(
  jsonString: string,
): SafeParseResult<BridgePhrasesConfigPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BridgePhrasesConfigPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BridgePhrasesConfigPayload' from JSON`,
  );
}
