/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BridgePhrasesAgentInfo,
  BridgePhrasesAgentInfo$inboundSchema,
  BridgePhrasesAgentInfo$Outbound,
  BridgePhrasesAgentInfo$outboundSchema,
} from "./bridgephrasesagentinfo.js";
import {
  BridgePhrasesConfigPayload,
  BridgePhrasesConfigPayload$inboundSchema,
  BridgePhrasesConfigPayload$Outbound,
  BridgePhrasesConfigPayload$outboundSchema,
} from "./bridgephrasesconfigpayload.js";

/**
 * Response model for bridge phrases operations.
 *
 * @remarks
 *
 * A bridge phrases config is a named, sub-org-scoped collection of default bridge
 * phrases plus optional per-tool and per-language overrides that can be linked to an
 * agent. For more information, see
 * [Console docs](https://docs.syllable.ai/Resources/BridgePhrases).
 */
export type BridgePhrasesResponse = {
  /**
   * The name of the bridge phrases config.
   */
  name: string;
  /**
   * Description of the bridge phrases config.
   */
  description?: string | null | undefined;
  /**
   * The `config` JSONB payload stored on a bridge_phrases row.
   *
   * @remarks
   *
   * Holds the default phrases plus an inline list of per-tool overrides, each with
   * optional per-language (`localized`) overrides. Mirrors the shape documented in
   * docs/bridge-phrases-table-migration.md §5.2.
   */
  config?: BridgePhrasesConfigPayload | undefined;
  /**
   * The ID of the bridge phrases config to update.
   */
  id: number;
  /**
   * Comments for the most recent edit.
   */
  editComments?: string | null | undefined;
  /**
   * IDs and names of the agents linked to this bridge phrases config.
   */
  agentsInfo?: Array<BridgePhrasesAgentInfo> | null | undefined;
  /**
   * Timestamp of the last update.
   */
  updatedAt: Date;
  /**
   * Email of the user who last updated this config.
   */
  lastUpdatedBy: string;
};

/** @internal */
export const BridgePhrasesResponse$inboundSchema: z.ZodType<
  BridgePhrasesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  config: BridgePhrasesConfigPayload$inboundSchema.optional(),
  id: z.number().int(),
  edit_comments: z.nullable(z.string()).optional(),
  agents_info: z.nullable(z.array(BridgePhrasesAgentInfo$inboundSchema))
    .optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  last_updated_by: z.string(),
}).transform((v) => {
  return remap$(v, {
    "edit_comments": "editComments",
    "agents_info": "agentsInfo",
    "updated_at": "updatedAt",
    "last_updated_by": "lastUpdatedBy",
  });
});
/** @internal */
export type BridgePhrasesResponse$Outbound = {
  name: string;
  description?: string | null | undefined;
  config?: BridgePhrasesConfigPayload$Outbound | undefined;
  id: number;
  edit_comments?: string | null | undefined;
  agents_info?: Array<BridgePhrasesAgentInfo$Outbound> | null | undefined;
  updated_at: string;
  last_updated_by: string;
};

/** @internal */
export const BridgePhrasesResponse$outboundSchema: z.ZodType<
  BridgePhrasesResponse$Outbound,
  z.ZodTypeDef,
  BridgePhrasesResponse
> = z.object({
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  config: BridgePhrasesConfigPayload$outboundSchema.optional(),
  id: z.number().int(),
  editComments: z.nullable(z.string()).optional(),
  agentsInfo: z.nullable(z.array(BridgePhrasesAgentInfo$outboundSchema))
    .optional(),
  updatedAt: z.date().transform(v => v.toISOString()),
  lastUpdatedBy: z.string(),
}).transform((v) => {
  return remap$(v, {
    editComments: "edit_comments",
    agentsInfo: "agents_info",
    updatedAt: "updated_at",
    lastUpdatedBy: "last_updated_by",
  });
});

export function bridgePhrasesResponseToJSON(
  bridgePhrasesResponse: BridgePhrasesResponse,
): string {
  return JSON.stringify(
    BridgePhrasesResponse$outboundSchema.parse(bridgePhrasesResponse),
  );
}
export function bridgePhrasesResponseFromJSON(
  jsonString: string,
): SafeParseResult<BridgePhrasesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BridgePhrasesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BridgePhrasesResponse' from JSON`,
  );
}
