/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The communication service for a channel.
 */
export const ChannelServices = {
  Sip: "sip",
  Twilio: "twilio",
  Email: "email",
  Webchat: "webchat",
  Africastalking: "africastalking",
} as const;
/**
 * The communication service for a channel.
 */
export type ChannelServices = ClosedEnum<typeof ChannelServices>;

/** @internal */
export const ChannelServices$inboundSchema: z.ZodNativeEnum<
  typeof ChannelServices
> = z.nativeEnum(ChannelServices);
/** @internal */
export const ChannelServices$outboundSchema: z.ZodNativeEnum<
  typeof ChannelServices
> = ChannelServices$inboundSchema;
