/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Names of channel target fields supported for filtering on the full channel targets list
 *
 * @remarks
 * endpoint. Superset of [[ChannelTargetOrderProperties]] — includes filter-only fields like
 * ``target_mode_list`` that are not valid as ``order_by``.
 */
export const ChannelTargetProperties = {
  Id: "id",
  ChannelId: "channel_id",
  ChannelName: "channel_name",
  AgentId: "agent_id",
  Target: "target",
  TargetMode: "target_mode",
  TargetModeList: "target_mode_list",
  FallbackTarget: "fallback_target",
  IsTest: "is_test",
  UpdatedAt: "updated_at",
  A2pVerified: "a2p_verified",
} as const;
/**
 * Names of channel target fields supported for filtering on the full channel targets list
 *
 * @remarks
 * endpoint. Superset of [[ChannelTargetOrderProperties]] — includes filter-only fields like
 * ``target_mode_list`` that are not valid as ``order_by``.
 */
export type ChannelTargetProperties = ClosedEnum<
  typeof ChannelTargetProperties
>;

/** @internal */
export const ChannelTargetProperties$inboundSchema: z.ZodNativeEnum<
  typeof ChannelTargetProperties
> = z.nativeEnum(ChannelTargetProperties);
/** @internal */
export const ChannelTargetProperties$outboundSchema: z.ZodNativeEnum<
  typeof ChannelTargetProperties
> = ChannelTargetProperties$inboundSchema;
