/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CustomMessageUpdateRequest = {
  /**
   * The name of the custom message
   */
  name: string;
  /**
   * The text of the custom message
   */
  text: string;
  /**
   * The label of the custom message
   */
  label?: string | null | undefined;
  /**
   * The ID of the custom message
   */
  id: number;
  type?: string | undefined;
};

/** @internal */
export const CustomMessageUpdateRequest$inboundSchema: z.ZodType<
  CustomMessageUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  text: z.string(),
  label: z.nullable(z.string()).optional(),
  id: z.number().int(),
  type: z.string().default("greeting"),
});

/** @internal */
export type CustomMessageUpdateRequest$Outbound = {
  name: string;
  text: string;
  label?: string | null | undefined;
  id: number;
  type: string;
};

/** @internal */
export const CustomMessageUpdateRequest$outboundSchema: z.ZodType<
  CustomMessageUpdateRequest$Outbound,
  z.ZodTypeDef,
  CustomMessageUpdateRequest
> = z.object({
  name: z.string(),
  text: z.string(),
  label: z.nullable(z.string()).optional(),
  id: z.number().int(),
  type: z.string().default("greeting"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomMessageUpdateRequest$ {
  /** @deprecated use `CustomMessageUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = CustomMessageUpdateRequest$inboundSchema;
  /** @deprecated use `CustomMessageUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = CustomMessageUpdateRequest$outboundSchema;
  /** @deprecated use `CustomMessageUpdateRequest$Outbound` instead. */
  export type Outbound = CustomMessageUpdateRequest$Outbound;
}

export function customMessageUpdateRequestToJSON(
  customMessageUpdateRequest: CustomMessageUpdateRequest,
): string {
  return JSON.stringify(
    CustomMessageUpdateRequest$outboundSchema.parse(customMessageUpdateRequest),
  );
}

export function customMessageUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<CustomMessageUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomMessageUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomMessageUpdateRequest' from JSON`,
  );
}
