/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CustomMessageCreateRequest = {
  /**
   * The name of the custom message
   */
  name: string;
  /**
   * The text of the custom message
   */
  text: string;
  /**
   * The label of the custom message
   */
  label?: string | null | undefined;
  type?: string | undefined;
};

/** @internal */
export const CustomMessageCreateRequest$inboundSchema: z.ZodType<
  CustomMessageCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  text: z.string(),
  label: z.nullable(z.string()).optional(),
  type: z.string().default("greeting"),
});

/** @internal */
export type CustomMessageCreateRequest$Outbound = {
  name: string;
  text: string;
  label?: string | null | undefined;
  type: string;
};

/** @internal */
export const CustomMessageCreateRequest$outboundSchema: z.ZodType<
  CustomMessageCreateRequest$Outbound,
  z.ZodTypeDef,
  CustomMessageCreateRequest
> = z.object({
  name: z.string(),
  text: z.string(),
  label: z.nullable(z.string()).optional(),
  type: z.string().default("greeting"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomMessageCreateRequest$ {
  /** @deprecated use `CustomMessageCreateRequest$inboundSchema` instead. */
  export const inboundSchema = CustomMessageCreateRequest$inboundSchema;
  /** @deprecated use `CustomMessageCreateRequest$outboundSchema` instead. */
  export const outboundSchema = CustomMessageCreateRequest$outboundSchema;
  /** @deprecated use `CustomMessageCreateRequest$Outbound` instead. */
  export type Outbound = CustomMessageCreateRequest$Outbound;
}

export function customMessageCreateRequestToJSON(
  customMessageCreateRequest: CustomMessageCreateRequest,
): string {
  return JSON.stringify(
    CustomMessageCreateRequest$outboundSchema.parse(customMessageCreateRequest),
  );
}

export function customMessageCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<CustomMessageCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomMessageCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomMessageCreateRequest' from JSON`,
  );
}
