/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CustomMessageRule,
  CustomMessageRule$inboundSchema,
  CustomMessageRule$Outbound,
  CustomMessageRule$outboundSchema,
} from "./custommessagerule.js";
import {
  CustomMessageType,
  CustomMessageType$inboundSchema,
  CustomMessageType$outboundSchema,
} from "./custommessagetype.js";

/**
 * Request model to update an existing custom message.
 */
export type CustomMessageUpdateRequest = {
  /**
   * The name of the custom message
   */
  name: string;
  /**
   * Type of custom message. Greeting is for voice; email_template is for email (subject + body).
   */
  type?: CustomMessageType | undefined;
  /**
   * An optional preamble that will be delivered before the main message, regardless of whether the current time and date match a rule or the system uses the default message. Cannot contain the "{{ language.mode }}" tag. In the case of a voice conversation, the user will not be able to interrupt the preamble. Can be used for e.g. legal disclaimers that the user must always see/hear.
   */
  preamble?: string | null | undefined;
  /**
   * The default message that the agent will deliver if no rules are set or no rules match the current timestamp. For email_template, this is the body.
   */
  text: string;
  /**
   * Email subject. Required for email_template (in type_config); ignored otherwise.
   */
  subject?: string | null | undefined;
  /**
   * The label of the custom message
   */
  label?: string | null | undefined;
  /**
   * Rules for time-specific message variants
   */
  rules?: Array<CustomMessageRule> | undefined;
  /**
   * The ID of the custom message
   */
  id: number;
};

/** @internal */
export const CustomMessageUpdateRequest$inboundSchema: z.ZodType<
  CustomMessageUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  type: CustomMessageType$inboundSchema.optional(),
  preamble: z.nullable(z.string()).optional(),
  text: z.string(),
  subject: z.nullable(z.string()).optional(),
  label: z.nullable(z.string()).optional(),
  rules: z.array(CustomMessageRule$inboundSchema).optional(),
  id: z.number().int(),
});
/** @internal */
export type CustomMessageUpdateRequest$Outbound = {
  name: string;
  type?: string | undefined;
  preamble?: string | null | undefined;
  text: string;
  subject?: string | null | undefined;
  label?: string | null | undefined;
  rules?: Array<CustomMessageRule$Outbound> | undefined;
  id: number;
};

/** @internal */
export const CustomMessageUpdateRequest$outboundSchema: z.ZodType<
  CustomMessageUpdateRequest$Outbound,
  z.ZodTypeDef,
  CustomMessageUpdateRequest
> = z.object({
  name: z.string(),
  type: CustomMessageType$outboundSchema.optional(),
  preamble: z.nullable(z.string()).optional(),
  text: z.string(),
  subject: z.nullable(z.string()).optional(),
  label: z.nullable(z.string()).optional(),
  rules: z.array(CustomMessageRule$outboundSchema).optional(),
  id: z.number().int(),
});

export function customMessageUpdateRequestToJSON(
  customMessageUpdateRequest: CustomMessageUpdateRequest,
): string {
  return JSON.stringify(
    CustomMessageUpdateRequest$outboundSchema.parse(customMessageUpdateRequest),
  );
}
export function customMessageUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<CustomMessageUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomMessageUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomMessageUpdateRequest' from JSON`,
  );
}
