/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Deprecated.  Please update to use DashboardTokenResponse.
 *
 * @remarks
 * Basic information about a dashboard.
 */
export type Dashboard = {
  /**
   * Superset embedded ID of the dashboard
   */
  embeddedId: string;
  /**
   * Superset guest token of the dashboard
   */
  guestToken: string;
  /**
   * Name of the dashboard
   */
  name: string;
  /**
   * Superset URL of the dashboard
   */
  supersetUrl: string;
};

/** @internal */
export const Dashboard$inboundSchema: z.ZodType<
  Dashboard,
  z.ZodTypeDef,
  unknown
> = z.object({
  embedded_id: z.string(),
  guest_token: z.string(),
  name: z.string(),
  superset_url: z.string(),
}).transform((v) => {
  return remap$(v, {
    "embedded_id": "embeddedId",
    "guest_token": "guestToken",
    "superset_url": "supersetUrl",
  });
});
/** @internal */
export type Dashboard$Outbound = {
  embedded_id: string;
  guest_token: string;
  name: string;
  superset_url: string;
};

/** @internal */
export const Dashboard$outboundSchema: z.ZodType<
  Dashboard$Outbound,
  z.ZodTypeDef,
  Dashboard
> = z.object({
  embeddedId: z.string(),
  guestToken: z.string(),
  name: z.string(),
  supersetUrl: z.string(),
}).transform((v) => {
  return remap$(v, {
    embeddedId: "embedded_id",
    guestToken: "guest_token",
    supersetUrl: "superset_url",
  });
});

export function dashboardToJSON(dashboard: Dashboard): string {
  return JSON.stringify(Dashboard$outboundSchema.parse(dashboard));
}
export function dashboardFromJSON(
  jsonString: string,
): SafeParseResult<Dashboard, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Dashboard$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Dashboard' from JSON`,
  );
}
