/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Basic information about a dashboard with a description.
 */
export type DashboardResponse = {
  /**
   * Name of the dashboard
   */
  name: string;
  /**
   * Display name of the dashboard
   */
  displayName: string;
  /**
   * Dashboard importance (0 is the highest)
   */
  rank: number;
  /**
   * Dashboard label. Typically "report" or "dashboard"
   */
  label: string;
};

/** @internal */
export const DashboardResponse$inboundSchema: z.ZodType<
  DashboardResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  display_name: z.string(),
  rank: z.number().int(),
  label: z.string(),
}).transform((v) => {
  return remap$(v, {
    "display_name": "displayName",
  });
});
/** @internal */
export type DashboardResponse$Outbound = {
  name: string;
  display_name: string;
  rank: number;
  label: string;
};

/** @internal */
export const DashboardResponse$outboundSchema: z.ZodType<
  DashboardResponse$Outbound,
  z.ZodTypeDef,
  DashboardResponse
> = z.object({
  name: z.string(),
  displayName: z.string(),
  rank: z.number().int(),
  label: z.string(),
}).transform((v) => {
  return remap$(v, {
    displayName: "display_name",
  });
});

export function dashboardResponseToJSON(
  dashboardResponse: DashboardResponse,
): string {
  return JSON.stringify(
    DashboardResponse$outboundSchema.parse(dashboardResponse),
  );
}
export function dashboardResponseFromJSON(
  jsonString: string,
): SafeParseResult<DashboardResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DashboardResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DashboardResponse' from JSON`,
  );
}
