/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Names of data source fields supported for filtering/sorting on list endpoint.
 */
export const DataSourceProperties = {
  Name: "name",
  Description: "description",
  Labels: "labels",
  Chunk: "chunk",
  ChunkDelimiter: "chunk_delimiter",
  UpdatedAt: "updated_at",
  LastUpdatedBy: "last_updated_by",
} as const;
/**
 * Names of data source fields supported for filtering/sorting on list endpoint.
 */
export type DataSourceProperties = ClosedEnum<typeof DataSourceProperties>;

/** @internal */
export const DataSourceProperties$inboundSchema: z.ZodNativeEnum<
  typeof DataSourceProperties
> = z.nativeEnum(DataSourceProperties);
/** @internal */
export const DataSourceProperties$outboundSchema: z.ZodNativeEnum<
  typeof DataSourceProperties
> = DataSourceProperties$inboundSchema;
