/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Available options for day of the week for use in message rules.
 */
export const DayOfWeek = {
  Mo: "mo",
  Tu: "tu",
  We: "we",
  Th: "th",
  Fr: "fr",
  Sa: "sa",
  Su: "su",
} as const;
/**
 * Available options for day of the week for use in message rules.
 */
export type DayOfWeek = ClosedEnum<typeof DayOfWeek>;

/** @internal */
export const DayOfWeek$inboundSchema: z.ZodNativeEnum<typeof DayOfWeek> = z
  .nativeEnum(DayOfWeek);

/** @internal */
export const DayOfWeek$outboundSchema: z.ZodNativeEnum<typeof DayOfWeek> =
  DayOfWeek$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DayOfWeek$ {
  /** @deprecated use `DayOfWeek$inboundSchema` instead. */
  export const inboundSchema = DayOfWeek$inboundSchema;
  /** @deprecated use `DayOfWeek$outboundSchema` instead. */
  export const outboundSchema = DayOfWeek$outboundSchema;
}
