/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Enum representing days of the week.
 */
export const DaysOfWeek = {
  Mon: "mon",
  Tue: "tue",
  Wed: "wed",
  Thu: "thu",
  Fri: "fri",
  Sat: "sat",
  Sun: "sun",
} as const;
/**
 * Enum representing days of the week.
 */
export type DaysOfWeek = ClosedEnum<typeof DaysOfWeek>;

/** @internal */
export const DaysOfWeek$inboundSchema: z.ZodNativeEnum<typeof DaysOfWeek> = z
  .nativeEnum(DaysOfWeek);

/** @internal */
export const DaysOfWeek$outboundSchema: z.ZodNativeEnum<typeof DaysOfWeek> =
  DaysOfWeek$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DaysOfWeek$ {
  /** @deprecated use `DaysOfWeek$inboundSchema` instead. */
  export const inboundSchema = DaysOfWeek$inboundSchema;
  /** @deprecated use `DaysOfWeek$outboundSchema` instead. */
  export const outboundSchema = DaysOfWeek$outboundSchema;
}
