/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Audit metadata associated with a dictionary.
 */
export type DictionaryMetadata = {
  entries: number;
  hash: string;
  source?: string | undefined;
};

/** @internal */
export const DictionaryMetadata$inboundSchema: z.ZodType<
  DictionaryMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  entries: z.number().int(),
  hash: z.string(),
  source: z.string().default(""),
});
/** @internal */
export type DictionaryMetadata$Outbound = {
  entries: number;
  hash: string;
  source: string;
};

/** @internal */
export const DictionaryMetadata$outboundSchema: z.ZodType<
  DictionaryMetadata$Outbound,
  z.ZodTypeDef,
  DictionaryMetadata
> = z.object({
  entries: z.number().int(),
  hash: z.string(),
  source: z.string().default(""),
});

export function dictionaryMetadataToJSON(
  dictionaryMetadata: DictionaryMetadata,
): string {
  return JSON.stringify(
    DictionaryMetadata$outboundSchema.parse(dictionaryMetadata),
  );
}
export function dictionaryMetadataFromJSON(
  jsonString: string,
): SafeParseResult<DictionaryMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DictionaryMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DictionaryMetadata' from JSON`,
  );
}
