/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Numbers = {};

export type DirectoryExtension = {
  name: string;
  numbers?: Array<Numbers> | null | undefined;
};

/** @internal */
export const Numbers$inboundSchema: z.ZodType<Numbers, z.ZodTypeDef, unknown> =
  z.object({});

/** @internal */
export type Numbers$Outbound = {};

/** @internal */
export const Numbers$outboundSchema: z.ZodType<
  Numbers$Outbound,
  z.ZodTypeDef,
  Numbers
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Numbers$ {
  /** @deprecated use `Numbers$inboundSchema` instead. */
  export const inboundSchema = Numbers$inboundSchema;
  /** @deprecated use `Numbers$outboundSchema` instead. */
  export const outboundSchema = Numbers$outboundSchema;
  /** @deprecated use `Numbers$Outbound` instead. */
  export type Outbound = Numbers$Outbound;
}

export function numbersToJSON(numbers: Numbers): string {
  return JSON.stringify(Numbers$outboundSchema.parse(numbers));
}

export function numbersFromJSON(
  jsonString: string,
): SafeParseResult<Numbers, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Numbers$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Numbers' from JSON`,
  );
}

/** @internal */
export const DirectoryExtension$inboundSchema: z.ZodType<
  DirectoryExtension,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  numbers: z.nullable(z.array(z.lazy(() => Numbers$inboundSchema))).optional(),
});

/** @internal */
export type DirectoryExtension$Outbound = {
  name: string;
  numbers?: Array<Numbers$Outbound> | null | undefined;
};

/** @internal */
export const DirectoryExtension$outboundSchema: z.ZodType<
  DirectoryExtension$Outbound,
  z.ZodTypeDef,
  DirectoryExtension
> = z.object({
  name: z.string(),
  numbers: z.nullable(z.array(z.lazy(() => Numbers$outboundSchema))).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DirectoryExtension$ {
  /** @deprecated use `DirectoryExtension$inboundSchema` instead. */
  export const inboundSchema = DirectoryExtension$inboundSchema;
  /** @deprecated use `DirectoryExtension$outboundSchema` instead. */
  export const outboundSchema = DirectoryExtension$outboundSchema;
  /** @deprecated use `DirectoryExtension$Outbound` instead. */
  export type Outbound = DirectoryExtension$Outbound;
}

export function directoryExtensionToJSON(
  directoryExtension: DirectoryExtension,
): string {
  return JSON.stringify(
    DirectoryExtension$outboundSchema.parse(directoryExtension),
  );
}

export function directoryExtensionFromJSON(
  jsonString: string,
): SafeParseResult<DirectoryExtension, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DirectoryExtension$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DirectoryExtension' from JSON`,
  );
}
