/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const DirectoryMemberStatus = {
  All: "all",
  Active: "active",
  Deleted: "deleted",
} as const;
export type DirectoryMemberStatus = ClosedEnum<typeof DirectoryMemberStatus>;

/** @internal */
export const DirectoryMemberStatus$inboundSchema: z.ZodNativeEnum<
  typeof DirectoryMemberStatus
> = z.nativeEnum(DirectoryMemberStatus);
/** @internal */
export const DirectoryMemberStatus$outboundSchema: z.ZodNativeEnum<
  typeof DirectoryMemberStatus
> = DirectoryMemberStatus$inboundSchema;
