/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DisplayValueSource,
  DisplayValueSource$inboundSchema,
  DisplayValueSource$Outbound,
  DisplayValueSource$outboundSchema,
} from "./displayvaluesource.js";

export type DisplayCtaMappingText =
  | string
  | number
  | number
  | boolean
  | DisplayValueSource;

export const DisplayCtaMappingIcon = {
  Phone: "phone",
  Email: "email",
  Chat: "chat",
  Calendar: "calendar",
  Arrow: "arrow",
} as const;
export type DisplayCtaMappingIcon = ClosedEnum<typeof DisplayCtaMappingIcon>;

export type DisplayCtaMappingLink =
  | string
  | number
  | number
  | boolean
  | DisplayValueSource;

export type DisplayCtaMappingActionid =
  | string
  | number
  | number
  | boolean
  | DisplayValueSource;

export type DisplayCtaMappingMessage =
  | string
  | number
  | number
  | boolean
  | DisplayValueSource;

export type DisplayCtaMapping = {
  text?: string | number | number | boolean | DisplayValueSource | undefined;
  icon?: DisplayCtaMappingIcon | undefined;
  link?: string | number | number | boolean | DisplayValueSource | undefined;
  actionId?:
    | string
    | number
    | number
    | boolean
    | DisplayValueSource
    | null
    | undefined;
  message?:
    | string
    | number
    | number
    | boolean
    | DisplayValueSource
    | null
    | undefined;
};

/** @internal */
export const DisplayCtaMappingText$inboundSchema: z.ZodType<
  DisplayCtaMappingText,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number().int(),
  z.number(),
  z.boolean(),
  DisplayValueSource$inboundSchema,
]);
/** @internal */
export type DisplayCtaMappingText$Outbound =
  | string
  | number
  | number
  | boolean
  | DisplayValueSource$Outbound;

/** @internal */
export const DisplayCtaMappingText$outboundSchema: z.ZodType<
  DisplayCtaMappingText$Outbound,
  z.ZodTypeDef,
  DisplayCtaMappingText
> = z.union([
  z.string(),
  z.number().int(),
  z.number(),
  z.boolean(),
  DisplayValueSource$outboundSchema,
]);

export function displayCtaMappingTextToJSON(
  displayCtaMappingText: DisplayCtaMappingText,
): string {
  return JSON.stringify(
    DisplayCtaMappingText$outboundSchema.parse(displayCtaMappingText),
  );
}
export function displayCtaMappingTextFromJSON(
  jsonString: string,
): SafeParseResult<DisplayCtaMappingText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisplayCtaMappingText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisplayCtaMappingText' from JSON`,
  );
}

/** @internal */
export const DisplayCtaMappingIcon$inboundSchema: z.ZodNativeEnum<
  typeof DisplayCtaMappingIcon
> = z.nativeEnum(DisplayCtaMappingIcon);
/** @internal */
export const DisplayCtaMappingIcon$outboundSchema: z.ZodNativeEnum<
  typeof DisplayCtaMappingIcon
> = DisplayCtaMappingIcon$inboundSchema;

/** @internal */
export const DisplayCtaMappingLink$inboundSchema: z.ZodType<
  DisplayCtaMappingLink,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number().int(),
  z.number(),
  z.boolean(),
  DisplayValueSource$inboundSchema,
]);
/** @internal */
export type DisplayCtaMappingLink$Outbound =
  | string
  | number
  | number
  | boolean
  | DisplayValueSource$Outbound;

/** @internal */
export const DisplayCtaMappingLink$outboundSchema: z.ZodType<
  DisplayCtaMappingLink$Outbound,
  z.ZodTypeDef,
  DisplayCtaMappingLink
> = z.union([
  z.string(),
  z.number().int(),
  z.number(),
  z.boolean(),
  DisplayValueSource$outboundSchema,
]);

export function displayCtaMappingLinkToJSON(
  displayCtaMappingLink: DisplayCtaMappingLink,
): string {
  return JSON.stringify(
    DisplayCtaMappingLink$outboundSchema.parse(displayCtaMappingLink),
  );
}
export function displayCtaMappingLinkFromJSON(
  jsonString: string,
): SafeParseResult<DisplayCtaMappingLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisplayCtaMappingLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisplayCtaMappingLink' from JSON`,
  );
}

/** @internal */
export const DisplayCtaMappingActionid$inboundSchema: z.ZodType<
  DisplayCtaMappingActionid,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number().int(),
  z.number(),
  z.boolean(),
  DisplayValueSource$inboundSchema,
]);
/** @internal */
export type DisplayCtaMappingActionid$Outbound =
  | string
  | number
  | number
  | boolean
  | DisplayValueSource$Outbound;

/** @internal */
export const DisplayCtaMappingActionid$outboundSchema: z.ZodType<
  DisplayCtaMappingActionid$Outbound,
  z.ZodTypeDef,
  DisplayCtaMappingActionid
> = z.union([
  z.string(),
  z.number().int(),
  z.number(),
  z.boolean(),
  DisplayValueSource$outboundSchema,
]);

export function displayCtaMappingActionidToJSON(
  displayCtaMappingActionid: DisplayCtaMappingActionid,
): string {
  return JSON.stringify(
    DisplayCtaMappingActionid$outboundSchema.parse(displayCtaMappingActionid),
  );
}
export function displayCtaMappingActionidFromJSON(
  jsonString: string,
): SafeParseResult<DisplayCtaMappingActionid, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisplayCtaMappingActionid$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisplayCtaMappingActionid' from JSON`,
  );
}

/** @internal */
export const DisplayCtaMappingMessage$inboundSchema: z.ZodType<
  DisplayCtaMappingMessage,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number().int(),
  z.number(),
  z.boolean(),
  DisplayValueSource$inboundSchema,
]);
/** @internal */
export type DisplayCtaMappingMessage$Outbound =
  | string
  | number
  | number
  | boolean
  | DisplayValueSource$Outbound;

/** @internal */
export const DisplayCtaMappingMessage$outboundSchema: z.ZodType<
  DisplayCtaMappingMessage$Outbound,
  z.ZodTypeDef,
  DisplayCtaMappingMessage
> = z.union([
  z.string(),
  z.number().int(),
  z.number(),
  z.boolean(),
  DisplayValueSource$outboundSchema,
]);

export function displayCtaMappingMessageToJSON(
  displayCtaMappingMessage: DisplayCtaMappingMessage,
): string {
  return JSON.stringify(
    DisplayCtaMappingMessage$outboundSchema.parse(displayCtaMappingMessage),
  );
}
export function displayCtaMappingMessageFromJSON(
  jsonString: string,
): SafeParseResult<DisplayCtaMappingMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisplayCtaMappingMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisplayCtaMappingMessage' from JSON`,
  );
}

/** @internal */
export const DisplayCtaMapping$inboundSchema: z.ZodType<
  DisplayCtaMapping,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.union([
    z.string(),
    z.number().int(),
    z.number(),
    z.boolean(),
    DisplayValueSource$inboundSchema,
  ]).optional(),
  icon: DisplayCtaMappingIcon$inboundSchema.default("arrow"),
  link: z.union([
    z.string(),
    z.number().int(),
    z.number(),
    z.boolean(),
    DisplayValueSource$inboundSchema,
  ]).optional(),
  actionId: z.nullable(
    z.union([
      z.string(),
      z.number().int(),
      z.number(),
      z.boolean(),
      DisplayValueSource$inboundSchema,
    ]),
  ).optional(),
  message: z.nullable(
    z.union([
      z.string(),
      z.number().int(),
      z.number(),
      z.boolean(),
      DisplayValueSource$inboundSchema,
    ]),
  ).optional(),
});
/** @internal */
export type DisplayCtaMapping$Outbound = {
  text?:
    | string
    | number
    | number
    | boolean
    | DisplayValueSource$Outbound
    | undefined;
  icon: string;
  link?:
    | string
    | number
    | number
    | boolean
    | DisplayValueSource$Outbound
    | undefined;
  actionId?:
    | string
    | number
    | number
    | boolean
    | DisplayValueSource$Outbound
    | null
    | undefined;
  message?:
    | string
    | number
    | number
    | boolean
    | DisplayValueSource$Outbound
    | null
    | undefined;
};

/** @internal */
export const DisplayCtaMapping$outboundSchema: z.ZodType<
  DisplayCtaMapping$Outbound,
  z.ZodTypeDef,
  DisplayCtaMapping
> = z.object({
  text: z.union([
    z.string(),
    z.number().int(),
    z.number(),
    z.boolean(),
    DisplayValueSource$outboundSchema,
  ]).optional(),
  icon: DisplayCtaMappingIcon$outboundSchema.default("arrow"),
  link: z.union([
    z.string(),
    z.number().int(),
    z.number(),
    z.boolean(),
    DisplayValueSource$outboundSchema,
  ]).optional(),
  actionId: z.nullable(
    z.union([
      z.string(),
      z.number().int(),
      z.number(),
      z.boolean(),
      DisplayValueSource$outboundSchema,
    ]),
  ).optional(),
  message: z.nullable(
    z.union([
      z.string(),
      z.number().int(),
      z.number(),
      z.boolean(),
      DisplayValueSource$outboundSchema,
    ]),
  ).optional(),
});

export function displayCtaMappingToJSON(
  displayCtaMapping: DisplayCtaMapping,
): string {
  return JSON.stringify(
    DisplayCtaMapping$outboundSchema.parse(displayCtaMapping),
  );
}
export function displayCtaMappingFromJSON(
  jsonString: string,
): SafeParseResult<DisplayCtaMapping, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisplayCtaMapping$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisplayCtaMapping' from JSON`,
  );
}
