/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CallAction,
  CallAction$inboundSchema,
  CallAction$Outbound,
  CallAction$outboundSchema,
} from "./callaction.js";
import {
  IncrementAction,
  IncrementAction$inboundSchema,
  IncrementAction$Outbound,
  IncrementAction$outboundSchema,
} from "./incrementaction.js";
import {
  SaveAction,
  SaveAction$inboundSchema,
  SaveAction$Outbound,
  SaveAction$outboundSchema,
} from "./saveaction.js";
import {
  SayAction,
  SayAction$inboundSchema,
  SayAction$Outbound,
  SayAction$outboundSchema,
} from "./sayaction.js";
import {
  SetValueAction,
  SetValueAction$inboundSchema,
  SetValueAction$Outbound,
  SetValueAction$outboundSchema,
} from "./setvalueaction.js";

export type Start =
  | (CallAction & { action: "call" })
  | (IncrementAction & { action: "inc" })
  | (SayAction & { action: "say" })
  | (SetValueAction & { action: "set" })
  | (SaveAction & { action: "save" });

export type Submit =
  | (CallAction & { action: "call" })
  | (IncrementAction & { action: "inc" })
  | (SayAction & { action: "say" })
  | (SetValueAction & { action: "set" })
  | (SaveAction & { action: "save" });

/**
 * Actions to perform when events occur (enter, submit).
 */
export type ExpressionTaskEvents = {
  /**
   * Actions to execute on the first input from the user.
   */
  start?:
    | Array<
      | (CallAction & { action: "call" })
      | (IncrementAction & { action: "inc" })
      | (SayAction & { action: "say" })
      | (SetValueAction & { action: "set" })
      | (SaveAction & { action: "save" })
    >
    | null
    | undefined;
  /**
   * Actions to execute when the tool/step is submitted by the LLM.
   */
  submit?:
    | Array<
      | (CallAction & { action: "call" })
      | (IncrementAction & { action: "inc" })
      | (SayAction & { action: "say" })
      | (SetValueAction & { action: "set" })
      | (SaveAction & { action: "save" })
    >
    | null
    | undefined;
};

/** @internal */
export const Start$inboundSchema: z.ZodType<Start, z.ZodTypeDef, unknown> = z
  .union([
    CallAction$inboundSchema.and(
      z.object({ action: z.literal("call") }).transform((v) => ({
        action: v.action,
      })),
    ),
    IncrementAction$inboundSchema.and(
      z.object({ action: z.literal("inc") }).transform((v) => ({
        action: v.action,
      })),
    ),
    SayAction$inboundSchema.and(
      z.object({ action: z.literal("say") }).transform((v) => ({
        action: v.action,
      })),
    ),
    SetValueAction$inboundSchema.and(
      z.object({ action: z.literal("set") }).transform((v) => ({
        action: v.action,
      })),
    ),
    SaveAction$inboundSchema.and(
      z.object({ action: z.literal("save") }).transform((v) => ({
        action: v.action,
      })),
    ),
  ]);
/** @internal */
export type Start$Outbound =
  | (CallAction$Outbound & { action: "call" })
  | (IncrementAction$Outbound & { action: "inc" })
  | (SayAction$Outbound & { action: "say" })
  | (SetValueAction$Outbound & { action: "set" })
  | (SaveAction$Outbound & { action: "save" });

/** @internal */
export const Start$outboundSchema: z.ZodType<
  Start$Outbound,
  z.ZodTypeDef,
  Start
> = z.union([
  CallAction$outboundSchema.and(
    z.object({ action: z.literal("call") }).transform((v) => ({
      action: v.action,
    })),
  ),
  IncrementAction$outboundSchema.and(
    z.object({ action: z.literal("inc") }).transform((v) => ({
      action: v.action,
    })),
  ),
  SayAction$outboundSchema.and(
    z.object({ action: z.literal("say") }).transform((v) => ({
      action: v.action,
    })),
  ),
  SetValueAction$outboundSchema.and(
    z.object({ action: z.literal("set") }).transform((v) => ({
      action: v.action,
    })),
  ),
  SaveAction$outboundSchema.and(
    z.object({ action: z.literal("save") }).transform((v) => ({
      action: v.action,
    })),
  ),
]);

export function startToJSON(start: Start): string {
  return JSON.stringify(Start$outboundSchema.parse(start));
}
export function startFromJSON(
  jsonString: string,
): SafeParseResult<Start, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Start$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Start' from JSON`,
  );
}

/** @internal */
export const Submit$inboundSchema: z.ZodType<Submit, z.ZodTypeDef, unknown> = z
  .union([
    CallAction$inboundSchema.and(
      z.object({ action: z.literal("call") }).transform((v) => ({
        action: v.action,
      })),
    ),
    IncrementAction$inboundSchema.and(
      z.object({ action: z.literal("inc") }).transform((v) => ({
        action: v.action,
      })),
    ),
    SayAction$inboundSchema.and(
      z.object({ action: z.literal("say") }).transform((v) => ({
        action: v.action,
      })),
    ),
    SetValueAction$inboundSchema.and(
      z.object({ action: z.literal("set") }).transform((v) => ({
        action: v.action,
      })),
    ),
    SaveAction$inboundSchema.and(
      z.object({ action: z.literal("save") }).transform((v) => ({
        action: v.action,
      })),
    ),
  ]);
/** @internal */
export type Submit$Outbound =
  | (CallAction$Outbound & { action: "call" })
  | (IncrementAction$Outbound & { action: "inc" })
  | (SayAction$Outbound & { action: "say" })
  | (SetValueAction$Outbound & { action: "set" })
  | (SaveAction$Outbound & { action: "save" });

/** @internal */
export const Submit$outboundSchema: z.ZodType<
  Submit$Outbound,
  z.ZodTypeDef,
  Submit
> = z.union([
  CallAction$outboundSchema.and(
    z.object({ action: z.literal("call") }).transform((v) => ({
      action: v.action,
    })),
  ),
  IncrementAction$outboundSchema.and(
    z.object({ action: z.literal("inc") }).transform((v) => ({
      action: v.action,
    })),
  ),
  SayAction$outboundSchema.and(
    z.object({ action: z.literal("say") }).transform((v) => ({
      action: v.action,
    })),
  ),
  SetValueAction$outboundSchema.and(
    z.object({ action: z.literal("set") }).transform((v) => ({
      action: v.action,
    })),
  ),
  SaveAction$outboundSchema.and(
    z.object({ action: z.literal("save") }).transform((v) => ({
      action: v.action,
    })),
  ),
]);

export function submitToJSON(submit: Submit): string {
  return JSON.stringify(Submit$outboundSchema.parse(submit));
}
export function submitFromJSON(
  jsonString: string,
): SafeParseResult<Submit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Submit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Submit' from JSON`,
  );
}

/** @internal */
export const ExpressionTaskEvents$inboundSchema: z.ZodType<
  ExpressionTaskEvents,
  z.ZodTypeDef,
  unknown
> = z.object({
  start: z.nullable(
    z.array(
      z.union([
        CallAction$inboundSchema.and(
          z.object({ action: z.literal("call") }).transform((v) => ({
            action: v.action,
          })),
        ),
        IncrementAction$inboundSchema.and(
          z.object({ action: z.literal("inc") }).transform((v) => ({
            action: v.action,
          })),
        ),
        SayAction$inboundSchema.and(
          z.object({ action: z.literal("say") }).transform((v) => ({
            action: v.action,
          })),
        ),
        SetValueAction$inboundSchema.and(
          z.object({ action: z.literal("set") }).transform((v) => ({
            action: v.action,
          })),
        ),
        SaveAction$inboundSchema.and(
          z.object({ action: z.literal("save") }).transform((v) => ({
            action: v.action,
          })),
        ),
      ]),
    ),
  ).optional(),
  submit: z.nullable(
    z.array(
      z.union([
        CallAction$inboundSchema.and(
          z.object({ action: z.literal("call") }).transform((v) => ({
            action: v.action,
          })),
        ),
        IncrementAction$inboundSchema.and(
          z.object({ action: z.literal("inc") }).transform((v) => ({
            action: v.action,
          })),
        ),
        SayAction$inboundSchema.and(
          z.object({ action: z.literal("say") }).transform((v) => ({
            action: v.action,
          })),
        ),
        SetValueAction$inboundSchema.and(
          z.object({ action: z.literal("set") }).transform((v) => ({
            action: v.action,
          })),
        ),
        SaveAction$inboundSchema.and(
          z.object({ action: z.literal("save") }).transform((v) => ({
            action: v.action,
          })),
        ),
      ]),
    ),
  ).optional(),
});
/** @internal */
export type ExpressionTaskEvents$Outbound = {
  start?:
    | Array<
      | (CallAction$Outbound & { action: "call" })
      | (IncrementAction$Outbound & { action: "inc" })
      | (SayAction$Outbound & { action: "say" })
      | (SetValueAction$Outbound & { action: "set" })
      | (SaveAction$Outbound & { action: "save" })
    >
    | null
    | undefined;
  submit?:
    | Array<
      | (CallAction$Outbound & { action: "call" })
      | (IncrementAction$Outbound & { action: "inc" })
      | (SayAction$Outbound & { action: "say" })
      | (SetValueAction$Outbound & { action: "set" })
      | (SaveAction$Outbound & { action: "save" })
    >
    | null
    | undefined;
};

/** @internal */
export const ExpressionTaskEvents$outboundSchema: z.ZodType<
  ExpressionTaskEvents$Outbound,
  z.ZodTypeDef,
  ExpressionTaskEvents
> = z.object({
  start: z.nullable(
    z.array(
      z.union([
        CallAction$outboundSchema.and(
          z.object({ action: z.literal("call") }).transform((v) => ({
            action: v.action,
          })),
        ),
        IncrementAction$outboundSchema.and(
          z.object({ action: z.literal("inc") }).transform((v) => ({
            action: v.action,
          })),
        ),
        SayAction$outboundSchema.and(
          z.object({ action: z.literal("say") }).transform((v) => ({
            action: v.action,
          })),
        ),
        SetValueAction$outboundSchema.and(
          z.object({ action: z.literal("set") }).transform((v) => ({
            action: v.action,
          })),
        ),
        SaveAction$outboundSchema.and(
          z.object({ action: z.literal("save") }).transform((v) => ({
            action: v.action,
          })),
        ),
      ]),
    ),
  ).optional(),
  submit: z.nullable(
    z.array(
      z.union([
        CallAction$outboundSchema.and(
          z.object({ action: z.literal("call") }).transform((v) => ({
            action: v.action,
          })),
        ),
        IncrementAction$outboundSchema.and(
          z.object({ action: z.literal("inc") }).transform((v) => ({
            action: v.action,
          })),
        ),
        SayAction$outboundSchema.and(
          z.object({ action: z.literal("say") }).transform((v) => ({
            action: v.action,
          })),
        ),
        SetValueAction$outboundSchema.and(
          z.object({ action: z.literal("set") }).transform((v) => ({
            action: v.action,
          })),
        ),
        SaveAction$outboundSchema.and(
          z.object({ action: z.literal("save") }).transform((v) => ({
            action: v.action,
          })),
        ),
      ]),
    ),
  ).optional(),
});

export function expressionTaskEventsToJSON(
  expressionTaskEvents: ExpressionTaskEvents,
): string {
  return JSON.stringify(
    ExpressionTaskEvents$outboundSchema.parse(expressionTaskEvents),
  );
}
export function expressionTaskEventsFromJSON(
  jsonString: string,
): SafeParseResult<ExpressionTaskEvents, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExpressionTaskEvents$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExpressionTaskEvents' from JSON`,
  );
}
