/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Request model to create a service incident.
 */
export type IncidentCreateRequest = {
  /**
   * Description of the service incident
   */
  description: string;
  /**
   * Start time of the incident
   */
  startDatetime: Date;
  /**
   * Resolution time of the incident
   */
  resolutionDatetime: Date;
  /**
   * Category of the impact
   */
  impactCategory: string;
  /**
   * Number of sessions impacted
   */
  sessionsImpacted: number;
  /**
   * Detailed markdown description of the incident
   */
  markdown: string;
  /**
   * The ID of the organization
   */
  organizationId?: number | null | undefined;
  /**
   * The ID of the sub-organization
   */
  subOrganizationId?: number | null | undefined;
  /**
   * The name of the sub-organization (DEPRECATED)
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  subOrganization?: string | null | undefined;
};

/** @internal */
export const IncidentCreateRequest$inboundSchema: z.ZodType<
  IncidentCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string(),
  start_datetime: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  resolution_datetime: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  impact_category: z.string(),
  sessions_impacted: z.number().int(),
  markdown: z.string(),
  organization_id: z.nullable(z.number().int()).optional(),
  sub_organization_id: z.nullable(z.number().int()).optional(),
  sub_organization: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "start_datetime": "startDatetime",
    "resolution_datetime": "resolutionDatetime",
    "impact_category": "impactCategory",
    "sessions_impacted": "sessionsImpacted",
    "organization_id": "organizationId",
    "sub_organization_id": "subOrganizationId",
    "sub_organization": "subOrganization",
  });
});

/** @internal */
export type IncidentCreateRequest$Outbound = {
  description: string;
  start_datetime: string;
  resolution_datetime: string;
  impact_category: string;
  sessions_impacted: number;
  markdown: string;
  organization_id?: number | null | undefined;
  sub_organization_id?: number | null | undefined;
  sub_organization?: string | null | undefined;
};

/** @internal */
export const IncidentCreateRequest$outboundSchema: z.ZodType<
  IncidentCreateRequest$Outbound,
  z.ZodTypeDef,
  IncidentCreateRequest
> = z.object({
  description: z.string(),
  startDatetime: z.date().transform(v => v.toISOString()),
  resolutionDatetime: z.date().transform(v => v.toISOString()),
  impactCategory: z.string(),
  sessionsImpacted: z.number().int(),
  markdown: z.string(),
  organizationId: z.nullable(z.number().int()).optional(),
  subOrganizationId: z.nullable(z.number().int()).optional(),
  subOrganization: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    startDatetime: "start_datetime",
    resolutionDatetime: "resolution_datetime",
    impactCategory: "impact_category",
    sessionsImpacted: "sessions_impacted",
    organizationId: "organization_id",
    subOrganizationId: "sub_organization_id",
    subOrganization: "sub_organization",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IncidentCreateRequest$ {
  /** @deprecated use `IncidentCreateRequest$inboundSchema` instead. */
  export const inboundSchema = IncidentCreateRequest$inboundSchema;
  /** @deprecated use `IncidentCreateRequest$outboundSchema` instead. */
  export const outboundSchema = IncidentCreateRequest$outboundSchema;
  /** @deprecated use `IncidentCreateRequest$Outbound` instead. */
  export type Outbound = IncidentCreateRequest$Outbound;
}

export function incidentCreateRequestToJSON(
  incidentCreateRequest: IncidentCreateRequest,
): string {
  return JSON.stringify(
    IncidentCreateRequest$outboundSchema.parse(incidentCreateRequest),
  );
}

export function incidentCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<IncidentCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IncidentCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IncidentCreateRequest' from JSON`,
  );
}
