/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Response model for a row in the insight_workflow_execution table.
 */
export type InsightWorkflowExecutionOutput = {
  /**
   * Unique ID of the workflow execution row
   */
  id: number;
  /**
   * ID of the workflow this execution belongs to
   */
  workflowId: number;
  /**
   * Status of the workflow execution
   */
  status: string;
  /**
   * Priority of the workflow execution
   */
  priority: number;
  /**
   * Session ID processed by this execution, if applicable
   */
  sessionId?: number | null | undefined;
  /**
   * Upload file ID processed by this execution, if applicable
   */
  uploadFileId?: number | null | undefined;
  /**
   * Number of times this execution has been retried
   */
  retryCount: number;
  /**
   * Error message from the last processing attempt, if any
   */
  errorMessage?: string | null | undefined;
  /**
   * Timestamp at which the most recent processing attempt started
   */
  startedAt?: Date | null | undefined;
  /**
   * Timestamp at which the execution row was created (i.e. when the work was queued)
   */
  createdAt: Date;
  /**
   * Event type that triggered the execution, if applicable
   */
  eventType?: string | null | undefined;
};

/** @internal */
export const InsightWorkflowExecutionOutput$inboundSchema: z.ZodType<
  InsightWorkflowExecutionOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  workflow_id: z.number().int(),
  status: z.string(),
  priority: z.number().int(),
  session_id: z.nullable(z.number().int()).optional(),
  upload_file_id: z.nullable(z.number().int()).optional(),
  retry_count: z.number().int(),
  error_message: z.nullable(z.string()).optional(),
  started_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  event_type: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "workflow_id": "workflowId",
    "session_id": "sessionId",
    "upload_file_id": "uploadFileId",
    "retry_count": "retryCount",
    "error_message": "errorMessage",
    "started_at": "startedAt",
    "created_at": "createdAt",
    "event_type": "eventType",
  });
});
/** @internal */
export type InsightWorkflowExecutionOutput$Outbound = {
  id: number;
  workflow_id: number;
  status: string;
  priority: number;
  session_id?: number | null | undefined;
  upload_file_id?: number | null | undefined;
  retry_count: number;
  error_message?: string | null | undefined;
  started_at?: string | null | undefined;
  created_at: string;
  event_type?: string | null | undefined;
};

/** @internal */
export const InsightWorkflowExecutionOutput$outboundSchema: z.ZodType<
  InsightWorkflowExecutionOutput$Outbound,
  z.ZodTypeDef,
  InsightWorkflowExecutionOutput
> = z.object({
  id: z.number().int(),
  workflowId: z.number().int(),
  status: z.string(),
  priority: z.number().int(),
  sessionId: z.nullable(z.number().int()).optional(),
  uploadFileId: z.nullable(z.number().int()).optional(),
  retryCount: z.number().int(),
  errorMessage: z.nullable(z.string()).optional(),
  startedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  createdAt: z.date().transform(v => v.toISOString()),
  eventType: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    workflowId: "workflow_id",
    sessionId: "session_id",
    uploadFileId: "upload_file_id",
    retryCount: "retry_count",
    errorMessage: "error_message",
    startedAt: "started_at",
    createdAt: "created_at",
    eventType: "event_type",
  });
});

export function insightWorkflowExecutionOutputToJSON(
  insightWorkflowExecutionOutput: InsightWorkflowExecutionOutput,
): string {
  return JSON.stringify(
    InsightWorkflowExecutionOutput$outboundSchema.parse(
      insightWorkflowExecutionOutput,
    ),
  );
}
export function insightWorkflowExecutionOutputFromJSON(
  jsonString: string,
): SafeParseResult<InsightWorkflowExecutionOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InsightWorkflowExecutionOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InsightWorkflowExecutionOutput' from JSON`,
  );
}
