/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const InsightToolProperties = {
  Id: "id",
  Name: "name",
  NameExact: "name_exact",
  Description: "description",
  ToolArguments: "tool_arguments",
  InsightToolDefinitionId: "insight_tool_definition_id",
  UpdatedAt: "updated_at",
} as const;
export type InsightToolProperties = ClosedEnum<typeof InsightToolProperties>;

/** @internal */
export const InsightToolProperties$inboundSchema: z.ZodNativeEnum<
  typeof InsightToolProperties
> = z.nativeEnum(InsightToolProperties);

/** @internal */
export const InsightToolProperties$outboundSchema: z.ZodNativeEnum<
  typeof InsightToolProperties
> = InsightToolProperties$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InsightToolProperties$ {
  /** @deprecated use `InsightToolProperties$inboundSchema` instead. */
  export const inboundSchema = InsightToolProperties$inboundSchema;
  /** @deprecated use `InsightToolProperties$outboundSchema` instead. */
  export const outboundSchema = InsightToolProperties$outboundSchema;
}
