/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Session identifier for workflow queue.
 */
export type InsightsWorkflowQueueSession = {
  /**
   * Unique name for workflow
   */
  workflowName: string;
  /**
   * List of session identifiers
   */
  sessionIdList?: Array<number> | null | undefined;
  /**
   * List of file IDs to be processed. This is only applicable for upload folders
   */
  fileIdList?: Array<number> | null | undefined;
};

/** @internal */
export const InsightsWorkflowQueueSession$inboundSchema: z.ZodType<
  InsightsWorkflowQueueSession,
  z.ZodTypeDef,
  unknown
> = z.object({
  workflow_name: z.string(),
  session_id_list: z.nullable(z.array(z.number().int())).optional(),
  file_id_list: z.nullable(z.array(z.number().int())).optional(),
}).transform((v) => {
  return remap$(v, {
    "workflow_name": "workflowName",
    "session_id_list": "sessionIdList",
    "file_id_list": "fileIdList",
  });
});
/** @internal */
export type InsightsWorkflowQueueSession$Outbound = {
  workflow_name: string;
  session_id_list?: Array<number> | null | undefined;
  file_id_list?: Array<number> | null | undefined;
};

/** @internal */
export const InsightsWorkflowQueueSession$outboundSchema: z.ZodType<
  InsightsWorkflowQueueSession$Outbound,
  z.ZodTypeDef,
  InsightsWorkflowQueueSession
> = z.object({
  workflowName: z.string(),
  sessionIdList: z.nullable(z.array(z.number().int())).optional(),
  fileIdList: z.nullable(z.array(z.number().int())).optional(),
}).transform((v) => {
  return remap$(v, {
    workflowName: "workflow_name",
    sessionIdList: "session_id_list",
    fileIdList: "file_id_list",
  });
});

export function insightsWorkflowQueueSessionToJSON(
  insightsWorkflowQueueSession: InsightsWorkflowQueueSession,
): string {
  return JSON.stringify(
    InsightsWorkflowQueueSession$outboundSchema.parse(
      insightsWorkflowQueueSession,
    ),
  );
}
export function insightsWorkflowQueueSessionFromJSON(
  jsonString: string,
): SafeParseResult<InsightsWorkflowQueueSession, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InsightsWorkflowQueueSession$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InsightsWorkflowQueueSession' from JSON`,
  );
}
