/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const InsightWorkflowProperties = {
  Id: "id",
  Name: "name",
  Description: "description",
  Status: "status",
  Conditions: "conditions",
  InsightToolIds: "insight_tool_ids",
  UpdatedAt: "updated_at",
} as const;
export type InsightWorkflowProperties = ClosedEnum<
  typeof InsightWorkflowProperties
>;

/** @internal */
export const InsightWorkflowProperties$inboundSchema: z.ZodNativeEnum<
  typeof InsightWorkflowProperties
> = z.nativeEnum(InsightWorkflowProperties);

/** @internal */
export const InsightWorkflowProperties$outboundSchema: z.ZodNativeEnum<
  typeof InsightWorkflowProperties
> = InsightWorkflowProperties$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InsightWorkflowProperties$ {
  /** @deprecated use `InsightWorkflowProperties$inboundSchema` instead. */
  export const inboundSchema = InsightWorkflowProperties$inboundSchema;
  /** @deprecated use `InsightWorkflowProperties$outboundSchema` instead. */
  export const outboundSchema = InsightWorkflowProperties$outboundSchema;
}
