/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const InsightToolProperties = {
  Id: "id",
  Name: "name",
  NameExact: "name_exact",
  Description: "description",
  ToolArguments: "tool_arguments",
  InsightToolDefinitionId: "insight_tool_definition_id",
  UpdatedAt: "updated_at",
} as const;
export type InsightToolProperties = ClosedEnum<typeof InsightToolProperties>;

/** @internal */
export const InsightToolProperties$inboundSchema: z.ZodNativeEnum<
  typeof InsightToolProperties
> = z.nativeEnum(InsightToolProperties);
/** @internal */
export const InsightToolProperties$outboundSchema: z.ZodNativeEnum<
  typeof InsightToolProperties
> = InsightToolProperties$inboundSchema;
