/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Friendly line-type buckets a campaign can be restricted to dial.
 *
 * @remarks
 *
 * These map to raw Twilio Lookup v2 line types via
 * ``lib.twilio.line_type_lookup.LINE_TYPE_BUCKETS``.
 */
export const LineTypeBucket = {
  Mobile: "mobile",
  Landline: "landline",
  Voip: "voip",
} as const;
/**
 * Friendly line-type buckets a campaign can be restricted to dial.
 *
 * @remarks
 *
 * These map to raw Twilio Lookup v2 line types via
 * ``lib.twilio.line_type_lookup.LINE_TYPE_BUCKETS``.
 */
export type LineTypeBucket = ClosedEnum<typeof LineTypeBucket>;

/** @internal */
export const LineTypeBucket$inboundSchema: z.ZodNativeEnum<
  typeof LineTypeBucket
> = z.nativeEnum(LineTypeBucket);
/** @internal */
export const LineTypeBucket$outboundSchema: z.ZodNativeEnum<
  typeof LineTypeBucket
> = LineTypeBucket$inboundSchema;
