/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  InsightWorkflowOutput,
  InsightWorkflowOutput$inboundSchema,
  InsightWorkflowOutput$Outbound,
  InsightWorkflowOutput$outboundSchema,
} from "./insightworkflowoutput.js";

export type ListResponseInsightWorkflowOutput = {
  /**
   * List of items returned from the query
   */
  items: Array<InsightWorkflowOutput>;
  /**
   * The page number of the results (0-based)
   */
  page: number;
  /**
   * The number of items returned per page
   */
  pageSize: number;
  /**
   * The total number of pages of results given the indicated page size
   */
  totalPages?: number | null | undefined;
  /**
   * The total number of items returned from the query
   */
  totalCount?: number | null | undefined;
};

/** @internal */
export const ListResponseInsightWorkflowOutput$inboundSchema: z.ZodType<
  ListResponseInsightWorkflowOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(InsightWorkflowOutput$inboundSchema),
  page: z.number().int(),
  page_size: z.number().int(),
  total_pages: z.nullable(z.number().int()).optional(),
  total_count: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "page_size": "pageSize",
    "total_pages": "totalPages",
    "total_count": "totalCount",
  });
});

/** @internal */
export type ListResponseInsightWorkflowOutput$Outbound = {
  items: Array<InsightWorkflowOutput$Outbound>;
  page: number;
  page_size: number;
  total_pages?: number | null | undefined;
  total_count?: number | null | undefined;
};

/** @internal */
export const ListResponseInsightWorkflowOutput$outboundSchema: z.ZodType<
  ListResponseInsightWorkflowOutput$Outbound,
  z.ZodTypeDef,
  ListResponseInsightWorkflowOutput
> = z.object({
  items: z.array(InsightWorkflowOutput$outboundSchema),
  page: z.number().int(),
  pageSize: z.number().int(),
  totalPages: z.nullable(z.number().int()).optional(),
  totalCount: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
    totalPages: "total_pages",
    totalCount: "total_count",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListResponseInsightWorkflowOutput$ {
  /** @deprecated use `ListResponseInsightWorkflowOutput$inboundSchema` instead. */
  export const inboundSchema = ListResponseInsightWorkflowOutput$inboundSchema;
  /** @deprecated use `ListResponseInsightWorkflowOutput$outboundSchema` instead. */
  export const outboundSchema =
    ListResponseInsightWorkflowOutput$outboundSchema;
  /** @deprecated use `ListResponseInsightWorkflowOutput$Outbound` instead. */
  export type Outbound = ListResponseInsightWorkflowOutput$Outbound;
}

export function listResponseInsightWorkflowOutputToJSON(
  listResponseInsightWorkflowOutput: ListResponseInsightWorkflowOutput,
): string {
  return JSON.stringify(
    ListResponseInsightWorkflowOutput$outboundSchema.parse(
      listResponseInsightWorkflowOutput,
    ),
  );
}

export function listResponseInsightWorkflowOutputFromJSON(
  jsonString: string,
): SafeParseResult<ListResponseInsightWorkflowOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResponseInsightWorkflowOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResponseInsightWorkflowOutput' from JSON`,
  );
}
