/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  LanguageGroupResponse,
  LanguageGroupResponse$inboundSchema,
  LanguageGroupResponse$Outbound,
  LanguageGroupResponse$outboundSchema,
} from "./languagegroupresponse.js";

export type ListResponseLanguageGroupResponse = {
  /**
   * List of items returned from the query
   */
  items: Array<LanguageGroupResponse>;
  /**
   * The page number of the results (0-based)
   */
  page: number;
  /**
   * The number of items returned per page
   */
  pageSize: number;
  /**
   * The total number of pages of results given the indicated page size
   */
  totalPages?: number | null | undefined;
  /**
   * The total number of items returned from the query
   */
  totalCount?: number | null | undefined;
};

/** @internal */
export const ListResponseLanguageGroupResponse$inboundSchema: z.ZodType<
  ListResponseLanguageGroupResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(LanguageGroupResponse$inboundSchema),
  page: z.number().int(),
  page_size: z.number().int(),
  total_pages: z.nullable(z.number().int()).optional(),
  total_count: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "page_size": "pageSize",
    "total_pages": "totalPages",
    "total_count": "totalCount",
  });
});

/** @internal */
export type ListResponseLanguageGroupResponse$Outbound = {
  items: Array<LanguageGroupResponse$Outbound>;
  page: number;
  page_size: number;
  total_pages?: number | null | undefined;
  total_count?: number | null | undefined;
};

/** @internal */
export const ListResponseLanguageGroupResponse$outboundSchema: z.ZodType<
  ListResponseLanguageGroupResponse$Outbound,
  z.ZodTypeDef,
  ListResponseLanguageGroupResponse
> = z.object({
  items: z.array(LanguageGroupResponse$outboundSchema),
  page: z.number().int(),
  pageSize: z.number().int(),
  totalPages: z.nullable(z.number().int()).optional(),
  totalCount: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
    totalPages: "total_pages",
    totalCount: "total_count",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListResponseLanguageGroupResponse$ {
  /** @deprecated use `ListResponseLanguageGroupResponse$inboundSchema` instead. */
  export const inboundSchema = ListResponseLanguageGroupResponse$inboundSchema;
  /** @deprecated use `ListResponseLanguageGroupResponse$outboundSchema` instead. */
  export const outboundSchema =
    ListResponseLanguageGroupResponse$outboundSchema;
  /** @deprecated use `ListResponseLanguageGroupResponse$Outbound` instead. */
  export type Outbound = ListResponseLanguageGroupResponse$Outbound;
}

export function listResponseLanguageGroupResponseToJSON(
  listResponseLanguageGroupResponse: ListResponseLanguageGroupResponse,
): string {
  return JSON.stringify(
    ListResponseLanguageGroupResponse$outboundSchema.parse(
      listResponseLanguageGroupResponse,
    ),
  );
}

export function listResponseLanguageGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListResponseLanguageGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResponseLanguageGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResponseLanguageGroupResponse' from JSON`,
  );
}
