/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ToolResponse,
  ToolResponse$inboundSchema,
  ToolResponse$Outbound,
  ToolResponse$outboundSchema,
} from "./toolresponse.js";

export type ListResponseToolResponse = {
  items: Array<ToolResponse>;
  page: number;
  pageSize: number;
  totalPages?: number | null | undefined;
  totalCount?: number | null | undefined;
};

/** @internal */
export const ListResponseToolResponse$inboundSchema: z.ZodType<
  ListResponseToolResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(ToolResponse$inboundSchema),
  page: z.number().int(),
  page_size: z.number().int(),
  total_pages: z.nullable(z.number().int()).optional(),
  total_count: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "page_size": "pageSize",
    "total_pages": "totalPages",
    "total_count": "totalCount",
  });
});

/** @internal */
export type ListResponseToolResponse$Outbound = {
  items: Array<ToolResponse$Outbound>;
  page: number;
  page_size: number;
  total_pages?: number | null | undefined;
  total_count?: number | null | undefined;
};

/** @internal */
export const ListResponseToolResponse$outboundSchema: z.ZodType<
  ListResponseToolResponse$Outbound,
  z.ZodTypeDef,
  ListResponseToolResponse
> = z.object({
  items: z.array(ToolResponse$outboundSchema),
  page: z.number().int(),
  pageSize: z.number().int(),
  totalPages: z.nullable(z.number().int()).optional(),
  totalCount: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
    totalPages: "total_pages",
    totalCount: "total_count",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListResponseToolResponse$ {
  /** @deprecated use `ListResponseToolResponse$inboundSchema` instead. */
  export const inboundSchema = ListResponseToolResponse$inboundSchema;
  /** @deprecated use `ListResponseToolResponse$outboundSchema` instead. */
  export const outboundSchema = ListResponseToolResponse$outboundSchema;
  /** @deprecated use `ListResponseToolResponse$Outbound` instead. */
  export type Outbound = ListResponseToolResponse$Outbound;
}

export function listResponseToolResponseToJSON(
  listResponseToolResponse: ListResponseToolResponse,
): string {
  return JSON.stringify(
    ListResponseToolResponse$outboundSchema.parse(listResponseToolResponse),
  );
}

export function listResponseToolResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListResponseToolResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResponseToolResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResponseToolResponse' from JSON`,
  );
}
