/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  Prompt,
  Prompt$inboundSchema,
  Prompt$Outbound,
  Prompt$outboundSchema,
} from "./prompt.js";

export type ListResponsePrompt = {
  items: Array<Prompt>;
  page: number;
  pageSize: number;
  totalPages: number;
  totalCount: number;
};

/** @internal */
export const ListResponsePrompt$inboundSchema: z.ZodType<
  ListResponsePrompt,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(Prompt$inboundSchema),
  page: z.number().int(),
  page_size: z.number().int(),
  total_pages: z.number().int(),
  total_count: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "page_size": "pageSize",
    "total_pages": "totalPages",
    "total_count": "totalCount",
  });
});

/** @internal */
export type ListResponsePrompt$Outbound = {
  items: Array<Prompt$Outbound>;
  page: number;
  page_size: number;
  total_pages: number;
  total_count: number;
};

/** @internal */
export const ListResponsePrompt$outboundSchema: z.ZodType<
  ListResponsePrompt$Outbound,
  z.ZodTypeDef,
  ListResponsePrompt
> = z.object({
  items: z.array(Prompt$outboundSchema),
  page: z.number().int(),
  pageSize: z.number().int(),
  totalPages: z.number().int(),
  totalCount: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
    totalPages: "total_pages",
    totalCount: "total_count",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListResponsePrompt$ {
  /** @deprecated use `ListResponsePrompt$inboundSchema` instead. */
  export const inboundSchema = ListResponsePrompt$inboundSchema;
  /** @deprecated use `ListResponsePrompt$outboundSchema` instead. */
  export const outboundSchema = ListResponsePrompt$outboundSchema;
  /** @deprecated use `ListResponsePrompt$Outbound` instead. */
  export type Outbound = ListResponsePrompt$Outbound;
}
