/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  Session,
  Session$inboundSchema,
  Session$Outbound,
  Session$outboundSchema,
} from "./session.js";

export type ListResponseSession = {
  items: Array<Session>;
  page: number;
  pageSize: number;
  totalPages?: number | null | undefined;
  totalCount?: number | null | undefined;
};

/** @internal */
export const ListResponseSession$inboundSchema: z.ZodType<
  ListResponseSession,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(Session$inboundSchema),
  page: z.number().int(),
  page_size: z.number().int(),
  total_pages: z.nullable(z.number().int()).optional(),
  total_count: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "page_size": "pageSize",
    "total_pages": "totalPages",
    "total_count": "totalCount",
  });
});

/** @internal */
export type ListResponseSession$Outbound = {
  items: Array<Session$Outbound>;
  page: number;
  page_size: number;
  total_pages?: number | null | undefined;
  total_count?: number | null | undefined;
};

/** @internal */
export const ListResponseSession$outboundSchema: z.ZodType<
  ListResponseSession$Outbound,
  z.ZodTypeDef,
  ListResponseSession
> = z.object({
  items: z.array(Session$outboundSchema),
  page: z.number().int(),
  pageSize: z.number().int(),
  totalPages: z.nullable(z.number().int()).optional(),
  totalCount: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
    totalPages: "total_pages",
    totalCount: "total_count",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListResponseSession$ {
  /** @deprecated use `ListResponseSession$inboundSchema` instead. */
  export const inboundSchema = ListResponseSession$inboundSchema;
  /** @deprecated use `ListResponseSession$outboundSchema` instead. */
  export const outboundSchema = ListResponseSession$outboundSchema;
  /** @deprecated use `ListResponseSession$Outbound` instead. */
  export type Outbound = ListResponseSession$Outbound;
}
