/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CaseExpression,
  CaseExpression$inboundSchema,
  CaseExpression$Outbound,
  CaseExpression$outboundSchema,
} from "./caseexpression.js";
import {
  CelExpression,
  CelExpression$inboundSchema,
  CelExpression$Outbound,
  CelExpression$outboundSchema,
} from "./celexpression.js";
import {
  JMESPathExpression,
  JMESPathExpression$inboundSchema,
  JMESPathExpression$Outbound,
  JMESPathExpression$outboundSchema,
} from "./jmespathexpression.js";

export type NextStepIf1 =
  | CelExpression
  | (JMESPathExpression & { type: "jmespath" })
  | (JMESPathExpression & { type: "jp" });

/**
 * An expression that must evaluate to true for the action to be applied.
 */
export type NextStepIf =
  | CaseExpression
  | CelExpression
  | (JMESPathExpression & { type: "jmespath" })
  | (JMESPathExpression & { type: "jp" })
  | string;

/**
 * Represents a conditional transition to the next step.
 */
export type NextStep = {
  /**
   * An expression that must evaluate to true for the action to be applied.
   */
  if?:
    | CaseExpression
    | CelExpression
    | (JMESPathExpression & { type: "jmespath" })
    | (JMESPathExpression & { type: "jp" })
    | string
    | null
    | undefined;
  /**
   * The identifier of the next step.
   */
  id: string;
  /**
   * List of input field names required for this transition. Validates that specified inputs are collected before allowing transition.
   */
  requires?: Array<string> | null | undefined;
};

/** @internal */
export const NextStepIf1$inboundSchema: z.ZodType<
  NextStepIf1,
  z.ZodTypeDef,
  unknown
> = z.union([
  CelExpression$inboundSchema,
  JMESPathExpression$inboundSchema.and(
    z.object({ type: z.literal("jmespath") }),
  ),
  JMESPathExpression$inboundSchema.and(z.object({ type: z.literal("jp") })),
]);
/** @internal */
export type NextStepIf1$Outbound =
  | CelExpression$Outbound
  | (JMESPathExpression$Outbound & { type: "jmespath" })
  | (JMESPathExpression$Outbound & { type: "jp" });

/** @internal */
export const NextStepIf1$outboundSchema: z.ZodType<
  NextStepIf1$Outbound,
  z.ZodTypeDef,
  NextStepIf1
> = z.union([
  CelExpression$outboundSchema,
  JMESPathExpression$outboundSchema.and(
    z.object({ type: z.literal("jmespath") }),
  ),
  JMESPathExpression$outboundSchema.and(z.object({ type: z.literal("jp") })),
]);

export function nextStepIf1ToJSON(nextStepIf1: NextStepIf1): string {
  return JSON.stringify(NextStepIf1$outboundSchema.parse(nextStepIf1));
}
export function nextStepIf1FromJSON(
  jsonString: string,
): SafeParseResult<NextStepIf1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NextStepIf1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NextStepIf1' from JSON`,
  );
}

/** @internal */
export const NextStepIf$inboundSchema: z.ZodType<
  NextStepIf,
  z.ZodTypeDef,
  unknown
> = z.union([
  CaseExpression$inboundSchema,
  z.union([
    CelExpression$inboundSchema,
    JMESPathExpression$inboundSchema.and(
      z.object({ type: z.literal("jmespath") }),
    ),
    JMESPathExpression$inboundSchema.and(z.object({ type: z.literal("jp") })),
  ]),
  z.string(),
]);
/** @internal */
export type NextStepIf$Outbound =
  | CaseExpression$Outbound
  | CelExpression$Outbound
  | (JMESPathExpression$Outbound & { type: "jmespath" })
  | (JMESPathExpression$Outbound & { type: "jp" })
  | string;

/** @internal */
export const NextStepIf$outboundSchema: z.ZodType<
  NextStepIf$Outbound,
  z.ZodTypeDef,
  NextStepIf
> = z.union([
  CaseExpression$outboundSchema,
  z.union([
    CelExpression$outboundSchema,
    JMESPathExpression$outboundSchema.and(
      z.object({ type: z.literal("jmespath") }),
    ),
    JMESPathExpression$outboundSchema.and(z.object({ type: z.literal("jp") })),
  ]),
  z.string(),
]);

export function nextStepIfToJSON(nextStepIf: NextStepIf): string {
  return JSON.stringify(NextStepIf$outboundSchema.parse(nextStepIf));
}
export function nextStepIfFromJSON(
  jsonString: string,
): SafeParseResult<NextStepIf, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NextStepIf$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NextStepIf' from JSON`,
  );
}

/** @internal */
export const NextStep$inboundSchema: z.ZodType<
  NextStep,
  z.ZodTypeDef,
  unknown
> = z.object({
  if: z.nullable(
    z.union([
      CaseExpression$inboundSchema,
      z.union([
        CelExpression$inboundSchema,
        JMESPathExpression$inboundSchema.and(
          z.object({ type: z.literal("jmespath") }),
        ),
        JMESPathExpression$inboundSchema.and(
          z.object({ type: z.literal("jp") }),
        ),
      ]),
      z.string(),
    ]),
  ).optional(),
  id: z.string(),
  requires: z.nullable(z.array(z.string())).optional(),
});
/** @internal */
export type NextStep$Outbound = {
  if?:
    | CaseExpression$Outbound
    | CelExpression$Outbound
    | (JMESPathExpression$Outbound & { type: "jmespath" })
    | (JMESPathExpression$Outbound & { type: "jp" })
    | string
    | null
    | undefined;
  id: string;
  requires?: Array<string> | null | undefined;
};

/** @internal */
export const NextStep$outboundSchema: z.ZodType<
  NextStep$Outbound,
  z.ZodTypeDef,
  NextStep
> = z.object({
  if: z.nullable(
    z.union([
      CaseExpression$outboundSchema,
      z.union([
        CelExpression$outboundSchema,
        JMESPathExpression$outboundSchema.and(
          z.object({ type: z.literal("jmespath") }),
        ),
        JMESPathExpression$outboundSchema.and(
          z.object({ type: z.literal("jp") }),
        ),
      ]),
      z.string(),
    ]),
  ).optional(),
  id: z.string(),
  requires: z.nullable(z.array(z.string())).optional(),
});

export function nextStepToJSON(nextStep: NextStep): string {
  return JSON.stringify(NextStep$outboundSchema.parse(nextStep));
}
export function nextStepFromJSON(
  jsonString: string,
): SafeParseResult<NextStep, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NextStep$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NextStep' from JSON`,
  );
}
