/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DaysOfWeek,
  DaysOfWeek$inboundSchema,
  DaysOfWeek$outboundSchema,
} from "./daysofweek.js";

export type OutboundCampaign = {
  /**
   * Human readable name of campaign
   */
  campaignName: string;
  /**
   * Description of campaign
   */
  description?: string | null | undefined;
  /**
   * Mode of the campaign (e.g. voice, sms)
   */
  mode?: string | null | undefined;
  /**
   * Time to live for SMS session in minutes
   */
  smsSessionTtl?: number | null | undefined;
  /**
   * Label for campaign (DEPRECATED - use labels instead)
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  label?: string | null | undefined;
  /**
   * Labels for campaign
   */
  labels?: Array<string> | null | undefined;
  /**
   * Variables for campaign
   */
  campaignVariables: { [k: string]: string };
  /**
   * Start time of campaign each day
   */
  dailyStartTime?: string | null | undefined;
  /**
   * End time of campaign each day
   */
  dailyEndTime?: string | null | undefined;
  /**
   * Source phone number, email, or SMS number
   */
  source?: string | null | undefined;
  /**
   * Caller ID for call
   */
  callerId: string | null;
  /**
   * Target number of outreach calls per hour
   */
  hourlyRate?: number | undefined;
  /**
   * Number of retries per target
   */
  retryCount?: number | undefined;
  /**
   * How long to wait before retrying
   */
  retryInterval?: string | null | undefined;
  /**
   * Days of the week when campaign is active
   */
  activeDays: Array<DaysOfWeek>;
  /**
   * Config for voicemail detection for voice campaigns. Set to None to disable.
   */
  voicemailDetection?: { [k: string]: number } | null | undefined;
  /**
   * Unique ID for campaign
   */
  id: number;
  /**
   * ID of agent assigned to campaign
   */
  agentId?: number | null | undefined;
  /**
   * Timestamp of campaign creation
   */
  createdAt?: Date | undefined;
  /**
   * Timestamp of campaign update
   */
  updatedAt?: Date | undefined;
  /**
   * Email of user who last updated campaign
   */
  lastUpdatedBy: string;
};

/** @internal */
export const OutboundCampaign$inboundSchema: z.ZodType<
  OutboundCampaign,
  z.ZodTypeDef,
  unknown
> = z.object({
  campaign_name: z.string(),
  description: z.nullable(z.string()).optional(),
  mode: z.nullable(z.string()).optional(),
  sms_session_ttl: z.nullable(z.number().int()).optional(),
  label: z.nullable(z.string()).optional(),
  labels: z.nullable(z.array(z.string())).optional(),
  campaign_variables: z.record(z.string()),
  daily_start_time: z.nullable(z.string()).optional(),
  daily_end_time: z.nullable(z.string()).optional(),
  source: z.nullable(z.string()).optional(),
  caller_id: z.nullable(z.string()),
  hourly_rate: z.number().int().default(1),
  retry_count: z.number().int().default(0),
  retry_interval: z.nullable(z.string()).optional(),
  active_days: z.array(DaysOfWeek$inboundSchema),
  voicemail_detection: z.nullable(z.record(z.number())).optional(),
  id: z.number().int(),
  agent_id: z.nullable(z.number().int()).optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  last_updated_by: z.string(),
}).transform((v) => {
  return remap$(v, {
    "campaign_name": "campaignName",
    "sms_session_ttl": "smsSessionTtl",
    "campaign_variables": "campaignVariables",
    "daily_start_time": "dailyStartTime",
    "daily_end_time": "dailyEndTime",
    "caller_id": "callerId",
    "hourly_rate": "hourlyRate",
    "retry_count": "retryCount",
    "retry_interval": "retryInterval",
    "active_days": "activeDays",
    "voicemail_detection": "voicemailDetection",
    "agent_id": "agentId",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "last_updated_by": "lastUpdatedBy",
  });
});
/** @internal */
export type OutboundCampaign$Outbound = {
  campaign_name: string;
  description?: string | null | undefined;
  mode?: string | null | undefined;
  sms_session_ttl?: number | null | undefined;
  label?: string | null | undefined;
  labels?: Array<string> | null | undefined;
  campaign_variables: { [k: string]: string };
  daily_start_time?: string | null | undefined;
  daily_end_time?: string | null | undefined;
  source?: string | null | undefined;
  caller_id: string | null;
  hourly_rate: number;
  retry_count: number;
  retry_interval?: string | null | undefined;
  active_days: Array<string>;
  voicemail_detection?: { [k: string]: number } | null | undefined;
  id: number;
  agent_id?: number | null | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
  last_updated_by: string;
};

/** @internal */
export const OutboundCampaign$outboundSchema: z.ZodType<
  OutboundCampaign$Outbound,
  z.ZodTypeDef,
  OutboundCampaign
> = z.object({
  campaignName: z.string(),
  description: z.nullable(z.string()).optional(),
  mode: z.nullable(z.string()).optional(),
  smsSessionTtl: z.nullable(z.number().int()).optional(),
  label: z.nullable(z.string()).optional(),
  labels: z.nullable(z.array(z.string())).optional(),
  campaignVariables: z.record(z.string()),
  dailyStartTime: z.nullable(z.string()).optional(),
  dailyEndTime: z.nullable(z.string()).optional(),
  source: z.nullable(z.string()).optional(),
  callerId: z.nullable(z.string()),
  hourlyRate: z.number().int().default(1),
  retryCount: z.number().int().default(0),
  retryInterval: z.nullable(z.string()).optional(),
  activeDays: z.array(DaysOfWeek$outboundSchema),
  voicemailDetection: z.nullable(z.record(z.number())).optional(),
  id: z.number().int(),
  agentId: z.nullable(z.number().int()).optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  updatedAt: z.date().transform(v => v.toISOString()).optional(),
  lastUpdatedBy: z.string(),
}).transform((v) => {
  return remap$(v, {
    campaignName: "campaign_name",
    smsSessionTtl: "sms_session_ttl",
    campaignVariables: "campaign_variables",
    dailyStartTime: "daily_start_time",
    dailyEndTime: "daily_end_time",
    callerId: "caller_id",
    hourlyRate: "hourly_rate",
    retryCount: "retry_count",
    retryInterval: "retry_interval",
    activeDays: "active_days",
    voicemailDetection: "voicemail_detection",
    agentId: "agent_id",
    createdAt: "created_at",
    updatedAt: "updated_at",
    lastUpdatedBy: "last_updated_by",
  });
});

export function outboundCampaignToJSON(
  outboundCampaign: OutboundCampaign,
): string {
  return JSON.stringify(
    OutboundCampaign$outboundSchema.parse(outboundCampaign),
  );
}
export function outboundCampaignFromJSON(
  jsonString: string,
): SafeParseResult<OutboundCampaign, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutboundCampaign$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutboundCampaign' from JSON`,
  );
}
