/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  Prompt,
  Prompt$inboundSchema,
  Prompt$Outbound,
  Prompt$outboundSchema,
} from "./prompt.js";

export type PromptListResponse = {
  prompts: Array<Prompt>;
  filterName: string | null;
  page: number;
  pageSize: number;
  totalPages: number;
  totalCount: number;
};

/** @internal */
export const PromptListResponse$inboundSchema: z.ZodType<
  PromptListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  prompts: z.array(Prompt$inboundSchema),
  filter_name: z.nullable(z.string()),
  page: z.number().int(),
  page_size: z.number().int(),
  total_pages: z.number().int(),
  total_count: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "filter_name": "filterName",
    "page_size": "pageSize",
    "total_pages": "totalPages",
    "total_count": "totalCount",
  });
});

/** @internal */
export type PromptListResponse$Outbound = {
  prompts: Array<Prompt$Outbound>;
  filter_name: string | null;
  page: number;
  page_size: number;
  total_pages: number;
  total_count: number;
};

/** @internal */
export const PromptListResponse$outboundSchema: z.ZodType<
  PromptListResponse$Outbound,
  z.ZodTypeDef,
  PromptListResponse
> = z.object({
  prompts: z.array(Prompt$outboundSchema),
  filterName: z.nullable(z.string()),
  page: z.number().int(),
  pageSize: z.number().int(),
  totalPages: z.number().int(),
  totalCount: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    filterName: "filter_name",
    pageSize: "page_size",
    totalPages: "total_pages",
    totalCount: "total_count",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PromptListResponse$ {
  /** @deprecated use `PromptListResponse$inboundSchema` instead. */
  export const inboundSchema = PromptListResponse$inboundSchema;
  /** @deprecated use `PromptListResponse$outboundSchema` instead. */
  export const outboundSchema = PromptListResponse$outboundSchema;
  /** @deprecated use `PromptListResponse$Outbound` instead. */
  export type Outbound = PromptListResponse$Outbound;
}
