/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * LLM API provider.
 */
export const PromptLlmProvider = {
  AzureOpenai: "azure_openai",
  Openai: "openai",
} as const;
/**
 * LLM API provider.
 */
export type PromptLlmProvider = ClosedEnum<typeof PromptLlmProvider>;

/** @internal */
export const PromptLlmProvider$inboundSchema: z.ZodNativeEnum<
  typeof PromptLlmProvider
> = z.nativeEnum(PromptLlmProvider);

/** @internal */
export const PromptLlmProvider$outboundSchema: z.ZodNativeEnum<
  typeof PromptLlmProvider
> = PromptLlmProvider$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PromptLlmProvider$ {
  /** @deprecated use `PromptLlmProvider$inboundSchema` instead. */
  export const inboundSchema = PromptLlmProvider$inboundSchema;
  /** @deprecated use `PromptLlmProvider$outboundSchema` instead. */
  export const outboundSchema = PromptLlmProvider$outboundSchema;
}
