/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Status of a communication request.
 */
export const RequestStatus = {
  Pending: "PENDING",
  Duplicate: "DUPLICATE",
  Initiated: "INITIATED",
  Connected: "CONNECTED",
  CallCompleted: "CALL_COMPLETED",
  Failed: "FAILED",
  Canceled: "CANCELED",
  Invalid: "INVALID",
} as const;
/**
 * Status of a communication request.
 */
export type RequestStatus = ClosedEnum<typeof RequestStatus>;

/** @internal */
export const RequestStatus$inboundSchema: z.ZodNativeEnum<
  typeof RequestStatus
> = z.nativeEnum(RequestStatus);
/** @internal */
export const RequestStatus$outboundSchema: z.ZodNativeEnum<
  typeof RequestStatus
> = RequestStatus$inboundSchema;
