/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CaseExpression,
  CaseExpression$inboundSchema,
  CaseExpression$Outbound,
  CaseExpression$outboundSchema,
} from "./caseexpression.js";
import {
  CelExpression,
  CelExpression$inboundSchema,
  CelExpression$Outbound,
  CelExpression$outboundSchema,
} from "./celexpression.js";
import {
  JMESPathExpression,
  JMESPathExpression$inboundSchema,
  JMESPathExpression$Outbound,
  JMESPathExpression$outboundSchema,
} from "./jmespathexpression.js";

export type SayActionIf1 =
  | CelExpression
  | (JMESPathExpression & { type: "jmespath" })
  | (JMESPathExpression & { type: "jp" });

/**
 * An expression that must evaluate to true for the action to be applied.
 */
export type SayActionIf =
  | CaseExpression
  | CelExpression
  | (JMESPathExpression & { type: "jmespath" })
  | (JMESPathExpression & { type: "jp" })
  | string;

/**
 * The role of the message.
 */
export const Role = {
  User: "user",
  Assistant: "assistant",
} as const;
/**
 * The role of the message.
 */
export type Role = ClosedEnum<typeof Role>;

export type SayAction = {
  /**
   * An expression that must evaluate to true for the action to be applied.
   */
  if?:
    | CaseExpression
    | CelExpression
    | (JMESPathExpression & { type: "jmespath" })
    | (JMESPathExpression & { type: "jp" })
    | string
    | null
    | undefined;
  /**
   * Text to apply if the condition is true.
   */
  text: string;
  action: "say";
  /**
   * The role of the message.
   */
  role?: Role | undefined;
};

/** @internal */
export const SayActionIf1$inboundSchema: z.ZodType<
  SayActionIf1,
  z.ZodTypeDef,
  unknown
> = z.union([
  CelExpression$inboundSchema,
  JMESPathExpression$inboundSchema.and(
    z.object({ type: z.literal("jmespath") }),
  ),
  JMESPathExpression$inboundSchema.and(z.object({ type: z.literal("jp") })),
]);
/** @internal */
export type SayActionIf1$Outbound =
  | CelExpression$Outbound
  | (JMESPathExpression$Outbound & { type: "jmespath" })
  | (JMESPathExpression$Outbound & { type: "jp" });

/** @internal */
export const SayActionIf1$outboundSchema: z.ZodType<
  SayActionIf1$Outbound,
  z.ZodTypeDef,
  SayActionIf1
> = z.union([
  CelExpression$outboundSchema,
  JMESPathExpression$outboundSchema.and(
    z.object({ type: z.literal("jmespath") }),
  ),
  JMESPathExpression$outboundSchema.and(z.object({ type: z.literal("jp") })),
]);

export function sayActionIf1ToJSON(sayActionIf1: SayActionIf1): string {
  return JSON.stringify(SayActionIf1$outboundSchema.parse(sayActionIf1));
}
export function sayActionIf1FromJSON(
  jsonString: string,
): SafeParseResult<SayActionIf1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SayActionIf1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SayActionIf1' from JSON`,
  );
}

/** @internal */
export const SayActionIf$inboundSchema: z.ZodType<
  SayActionIf,
  z.ZodTypeDef,
  unknown
> = z.union([
  CaseExpression$inboundSchema,
  z.union([
    CelExpression$inboundSchema,
    JMESPathExpression$inboundSchema.and(
      z.object({ type: z.literal("jmespath") }),
    ),
    JMESPathExpression$inboundSchema.and(z.object({ type: z.literal("jp") })),
  ]),
  z.string(),
]);
/** @internal */
export type SayActionIf$Outbound =
  | CaseExpression$Outbound
  | CelExpression$Outbound
  | (JMESPathExpression$Outbound & { type: "jmespath" })
  | (JMESPathExpression$Outbound & { type: "jp" })
  | string;

/** @internal */
export const SayActionIf$outboundSchema: z.ZodType<
  SayActionIf$Outbound,
  z.ZodTypeDef,
  SayActionIf
> = z.union([
  CaseExpression$outboundSchema,
  z.union([
    CelExpression$outboundSchema,
    JMESPathExpression$outboundSchema.and(
      z.object({ type: z.literal("jmespath") }),
    ),
    JMESPathExpression$outboundSchema.and(z.object({ type: z.literal("jp") })),
  ]),
  z.string(),
]);

export function sayActionIfToJSON(sayActionIf: SayActionIf): string {
  return JSON.stringify(SayActionIf$outboundSchema.parse(sayActionIf));
}
export function sayActionIfFromJSON(
  jsonString: string,
): SafeParseResult<SayActionIf, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SayActionIf$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SayActionIf' from JSON`,
  );
}

/** @internal */
export const Role$inboundSchema: z.ZodNativeEnum<typeof Role> = z.nativeEnum(
  Role,
);
/** @internal */
export const Role$outboundSchema: z.ZodNativeEnum<typeof Role> =
  Role$inboundSchema;

/** @internal */
export const SayAction$inboundSchema: z.ZodType<
  SayAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  if: z.nullable(
    z.union([
      CaseExpression$inboundSchema,
      z.union([
        CelExpression$inboundSchema,
        JMESPathExpression$inboundSchema.and(
          z.object({ type: z.literal("jmespath") }),
        ),
        JMESPathExpression$inboundSchema.and(
          z.object({ type: z.literal("jp") }),
        ),
      ]),
      z.string(),
    ]),
  ).optional(),
  text: z.string(),
  action: z.literal("say"),
  role: Role$inboundSchema.default("assistant"),
});
/** @internal */
export type SayAction$Outbound = {
  if?:
    | CaseExpression$Outbound
    | CelExpression$Outbound
    | (JMESPathExpression$Outbound & { type: "jmespath" })
    | (JMESPathExpression$Outbound & { type: "jp" })
    | string
    | null
    | undefined;
  text: string;
  action: "say";
  role: string;
};

/** @internal */
export const SayAction$outboundSchema: z.ZodType<
  SayAction$Outbound,
  z.ZodTypeDef,
  SayAction
> = z.object({
  if: z.nullable(
    z.union([
      CaseExpression$outboundSchema,
      z.union([
        CelExpression$outboundSchema,
        JMESPathExpression$outboundSchema.and(
          z.object({ type: z.literal("jmespath") }),
        ),
        JMESPathExpression$outboundSchema.and(
          z.object({ type: z.literal("jp") }),
        ),
      ]),
      z.string(),
    ]),
  ).optional(),
  text: z.string(),
  action: z.literal("say"),
  role: Role$outboundSchema.default("assistant"),
});

export function sayActionToJSON(sayAction: SayAction): string {
  return JSON.stringify(SayAction$outboundSchema.parse(sayAction));
}
export function sayActionFromJSON(
  jsonString: string,
): SafeParseResult<SayAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SayAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SayAction' from JSON`,
  );
}
