/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SipTransport,
  SipTransport$inboundSchema,
  SipTransport$outboundSchema,
} from "./siptransport.js";

/**
 * A single SIP endpoint to attempt for a transfer.
 */
export type SipEndpoint = {
  /**
   * SIP endpoint host (IP address or hostname).
   */
  host: string;
  /**
   * SIP endpoint port.
   */
  port?: string | null | undefined;
  /**
   * SIP transport protocol, e.g. `tcp`, `tls` or `udp`.
   */
  transport?: SipTransport | null | undefined;
};

/** @internal */
export const SipEndpoint$inboundSchema: z.ZodType<
  SipEndpoint,
  z.ZodTypeDef,
  unknown
> = z.object({
  host: z.string(),
  port: z.nullable(z.string()).optional(),
  transport: z.nullable(SipTransport$inboundSchema).optional(),
});
/** @internal */
export type SipEndpoint$Outbound = {
  host: string;
  port?: string | null | undefined;
  transport?: string | null | undefined;
};

/** @internal */
export const SipEndpoint$outboundSchema: z.ZodType<
  SipEndpoint$Outbound,
  z.ZodTypeDef,
  SipEndpoint
> = z.object({
  host: z.string(),
  port: z.nullable(z.string()).optional(),
  transport: z.nullable(SipTransport$outboundSchema).optional(),
});

export function sipEndpointToJSON(sipEndpoint: SipEndpoint): string {
  return JSON.stringify(SipEndpoint$outboundSchema.parse(sipEndpoint));
}
export function sipEndpointFromJSON(
  jsonString: string,
): SafeParseResult<SipEndpoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SipEndpoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SipEndpoint' from JSON`,
  );
}
