/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The transport protocol to use for the SIP endpoint.
 */
export const SipTransport = {
  Tls: "tls",
  Tcp: "tcp",
  Udp: "udp",
} as const;
/**
 * The transport protocol to use for the SIP endpoint.
 */
export type SipTransport = ClosedEnum<typeof SipTransport>;

/** @internal */
export const SipTransport$inboundSchema: z.ZodNativeEnum<typeof SipTransport> =
  z.nativeEnum(SipTransport);
/** @internal */
export const SipTransport$outboundSchema: z.ZodNativeEnum<typeof SipTransport> =
  SipTransport$inboundSchema;
