/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type Response = {};

export type TestMessageResponse = {
  testId: string;
  agentId: string;
  text: string;
  response?: Response | undefined;
};

/** @internal */
export const Response$inboundSchema: z.ZodType<
  Response,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type Response$Outbound = {};

/** @internal */
export const Response$outboundSchema: z.ZodType<
  Response$Outbound,
  z.ZodTypeDef,
  Response
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Response$ {
  /** @deprecated use `Response$inboundSchema` instead. */
  export const inboundSchema = Response$inboundSchema;
  /** @deprecated use `Response$outboundSchema` instead. */
  export const outboundSchema = Response$outboundSchema;
  /** @deprecated use `Response$Outbound` instead. */
  export type Outbound = Response$Outbound;
}

/** @internal */
export const TestMessageResponse$inboundSchema: z.ZodType<
  TestMessageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  test_id: z.string(),
  agent_id: z.string(),
  text: z.string(),
  response: z.lazy(() => Response$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "test_id": "testId",
    "agent_id": "agentId",
  });
});

/** @internal */
export type TestMessageResponse$Outbound = {
  test_id: string;
  agent_id: string;
  text: string;
  response?: Response$Outbound | undefined;
};

/** @internal */
export const TestMessageResponse$outboundSchema: z.ZodType<
  TestMessageResponse$Outbound,
  z.ZodTypeDef,
  TestMessageResponse
> = z.object({
  testId: z.string(),
  agentId: z.string(),
  text: z.string(),
  response: z.lazy(() => Response$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    testId: "test_id",
    agentId: "agent_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TestMessageResponse$ {
  /** @deprecated use `TestMessageResponse$inboundSchema` instead. */
  export const inboundSchema = TestMessageResponse$inboundSchema;
  /** @deprecated use `TestMessageResponse$outboundSchema` instead. */
  export const outboundSchema = TestMessageResponse$outboundSchema;
  /** @deprecated use `TestMessageResponse$Outbound` instead. */
  export type Outbound = TestMessageResponse$Outbound;
}
