/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ToolDetailResponse = {
  id: number;
  name: string;
  description: string;
  fields: Array<string>;
};

/** @internal */
export const ToolDetailResponse$inboundSchema: z.ZodType<
  ToolDetailResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  name: z.string(),
  description: z.string(),
  fields: z.array(z.string()),
});

/** @internal */
export type ToolDetailResponse$Outbound = {
  id: number;
  name: string;
  description: string;
  fields: Array<string>;
};

/** @internal */
export const ToolDetailResponse$outboundSchema: z.ZodType<
  ToolDetailResponse$Outbound,
  z.ZodTypeDef,
  ToolDetailResponse
> = z.object({
  id: z.number().int(),
  name: z.string(),
  description: z.string(),
  fields: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ToolDetailResponse$ {
  /** @deprecated use `ToolDetailResponse$inboundSchema` instead. */
  export const inboundSchema = ToolDetailResponse$inboundSchema;
  /** @deprecated use `ToolDetailResponse$outboundSchema` instead. */
  export const outboundSchema = ToolDetailResponse$outboundSchema;
  /** @deprecated use `ToolDetailResponse$Outbound` instead. */
  export type Outbound = ToolDetailResponse$Outbound;
}

export function toolDetailResponseToJSON(
  toolDetailResponse: ToolDetailResponse,
): string {
  return JSON.stringify(
    ToolDetailResponse$outboundSchema.parse(toolDetailResponse),
  );
}

export function toolDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<ToolDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolDetailResponse' from JSON`,
  );
}
