/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ToolParameterTransformCondition,
  ToolParameterTransformCondition$inboundSchema,
  ToolParameterTransformCondition$Outbound,
  ToolParameterTransformCondition$outboundSchema,
} from "./toolparametertransformcondition.js";

/**
 * The action to perform on the tool parameter value: `default` means only set the value (using the `format` field) if the parameter doesn't exist or is empty, `override` means always set the value," and `remove` means "remove the parameter value."
 */
export const ToolParameterTransformAction = {
  Default: "default",
  Override: "override",
  Remove: "remove",
} as const;
/**
 * The action to perform on the tool parameter value: `default` means only set the value (using the `format` field) if the parameter doesn't exist or is empty, `override` means always set the value," and `remove` means "remove the parameter value."
 */
export type ToolParameterTransformAction = ClosedEnum<
  typeof ToolParameterTransformAction
>;

/**
 * A transform to be applied to the value of a tool parameter.
 *
 * @remarks
 *
 * Either `value` or `format` must be set:
 * - `value` is any arbitrary value: string, list or dictionary.
 * - `format` is a string composed of other parameters or context variables.
 */
export type ToolParameterTransform = {
  /**
   * The action to perform on the tool parameter value: `default` means only set the value (using the `format` field) if the parameter doesn't exist or is empty, `override` means always set the value," and `remove` means "remove the parameter value."
   */
  action?: ToolParameterTransformAction | undefined;
  /**
   * Only apply the transform if the condition is met.
   */
  when?: ToolParameterTransformCondition | null | undefined;
  /**
   * The default value to use for the parameter.
   */
  value?: any | null | undefined;
  /**
   * The string value to use for the parameter. The value will be evaluated with the Python `str.format` method, for example, `Hello, {name}!`
   */
  format?: string | null | undefined;
};

/** @internal */
export const ToolParameterTransformAction$inboundSchema: z.ZodNativeEnum<
  typeof ToolParameterTransformAction
> = z.nativeEnum(ToolParameterTransformAction);
/** @internal */
export const ToolParameterTransformAction$outboundSchema: z.ZodNativeEnum<
  typeof ToolParameterTransformAction
> = ToolParameterTransformAction$inboundSchema;

/** @internal */
export const ToolParameterTransform$inboundSchema: z.ZodType<
  ToolParameterTransform,
  z.ZodTypeDef,
  unknown
> = z.object({
  action: ToolParameterTransformAction$inboundSchema.default("default"),
  when: z.nullable(ToolParameterTransformCondition$inboundSchema).optional(),
  value: z.nullable(z.any()).optional(),
  format: z.nullable(z.string()).optional(),
});
/** @internal */
export type ToolParameterTransform$Outbound = {
  action: string;
  when?: ToolParameterTransformCondition$Outbound | null | undefined;
  value?: any | null | undefined;
  format?: string | null | undefined;
};

/** @internal */
export const ToolParameterTransform$outboundSchema: z.ZodType<
  ToolParameterTransform$Outbound,
  z.ZodTypeDef,
  ToolParameterTransform
> = z.object({
  action: ToolParameterTransformAction$outboundSchema.default("default"),
  when: z.nullable(ToolParameterTransformCondition$outboundSchema).optional(),
  value: z.nullable(z.any()).optional(),
  format: z.nullable(z.string()).optional(),
});

export function toolParameterTransformToJSON(
  toolParameterTransform: ToolParameterTransform,
): string {
  return JSON.stringify(
    ToolParameterTransform$outboundSchema.parse(toolParameterTransform),
  );
}
export function toolParameterTransformFromJSON(
  jsonString: string,
): SafeParseResult<ToolParameterTransform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolParameterTransform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolParameterTransform' from JSON`,
  );
}
