/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  LoginType,
  LoginType$inboundSchema,
  LoginType$outboundSchema,
} from "./logintype.js";

/**
 * Request model to create a user.
 */
export type UserCreateRequest = {
  /**
   * Email address of the user
   */
  email: string;
  /**
   * First name of the user
   */
  firstName?: string | null | undefined;
  /**
   * Last name of the user
   */
  lastName?: string | null | undefined;
  /**
   * ID of the role assigned to the user
   */
  roleId: number;
  /**
   * The type of login to use for the user. If not provided, defaults to google for @gmail.com email addresses, and username and password otherwise.
   */
  loginType?: LoginType | null | undefined;
  /**
   * Whether to skip authentication for the user.
   */
  skipAuth?: boolean | undefined;
};

/** @internal */
export const UserCreateRequest$inboundSchema: z.ZodType<
  UserCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
  first_name: z.nullable(z.string()).optional(),
  last_name: z.nullable(z.string()).optional(),
  role_id: z.number().int(),
  login_type: z.nullable(LoginType$inboundSchema).optional(),
  skip_auth: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    "first_name": "firstName",
    "last_name": "lastName",
    "role_id": "roleId",
    "login_type": "loginType",
    "skip_auth": "skipAuth",
  });
});
/** @internal */
export type UserCreateRequest$Outbound = {
  email: string;
  first_name?: string | null | undefined;
  last_name?: string | null | undefined;
  role_id: number;
  login_type?: string | null | undefined;
  skip_auth: boolean;
};

/** @internal */
export const UserCreateRequest$outboundSchema: z.ZodType<
  UserCreateRequest$Outbound,
  z.ZodTypeDef,
  UserCreateRequest
> = z.object({
  email: z.string(),
  firstName: z.nullable(z.string()).optional(),
  lastName: z.nullable(z.string()).optional(),
  roleId: z.number().int(),
  loginType: z.nullable(LoginType$outboundSchema).optional(),
  skipAuth: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    firstName: "first_name",
    lastName: "last_name",
    roleId: "role_id",
    loginType: "login_type",
    skipAuth: "skip_auth",
  });
});

export function userCreateRequestToJSON(
  userCreateRequest: UserCreateRequest,
): string {
  return JSON.stringify(
    UserCreateRequest$outboundSchema.parse(userCreateRequest),
  );
}
export function userCreateRequestFromJSON(
  jsonString: string,
): SafeParseResult<UserCreateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserCreateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserCreateRequest' from JSON`,
  );
}
