name: Graduate SDK RC to Stable Version
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  workflow_dispatch:
    inputs:
      target_version:
        description: 'Target stable version (e.g., 1.0.0). Leave empty to graduate from current RC'
        type: string
        required: false
      target:
        description: 'optionally: set a specific target to generate, default is all'
        type: string
  

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      graduated_version: ${{ steps.extract.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract graduated version from gen.yaml
        id: extract
        run: |
          if [ -n "${{ github.event.inputs.target_version }}" ]; then
            echo "version=${{ github.event.inputs.target_version }}" >> $GITHUB_OUTPUT
          else
            # Extract version from gen.yaml and remove RC suffix
            VERSION=$(grep -E '^\s*version:\s*' .speakeasy/gen.yaml | sed 's/.*version:\s*//' | tr -d ' ')
            if [[ $VERSION == *"-rc"* ]]; then
              GRADUATED_VERSION=$(echo $VERSION | sed 's/-rc.*$//')
              echo "version=$GRADUATED_VERSION" >> $GITHUB_OUTPUT
              echo "Graduating from $VERSION to $GRADUATED_VERSION"
            else
              echo "version=$VERSION" >> $GITHUB_OUTPUT
              echo "Using existing version: $VERSION"
            fi
          fi

  graduate-and-generate:
    needs: extract-version
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: true
      mode: pr
      set_version: ${{ needs.extract-version.outputs.graduated_version }}
      target: ${{ github.event.inputs.target }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}