name: Graduate to Stable and Publish
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  workflow_dispatch:
    inputs:
      target_version:
        description: 'Target stable version (e.g., 1.0.0). Leave empty to graduate from current RC'
        type: string
        required: false
      target:
        description: 'Target SDK to graduate (default: syllable-sdk)'
        type: string
        required: false
        default: syllable-sdk

jobs:
  graduate-and-generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: true
      mode: direct
      set_version: ${{ github.event.inputs.target_version || 'graduate' }}
      target: ${{ github.event.inputs.target }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}

  # publish:
  #   needs: graduate-and-generate
  #   uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
  #   with:
  #     target: ${{ github.event.inputs.target }}
  #   secrets:
  #     github_access_token: ${{ secrets.GITHUB_TOKEN }}
  #     npm_token: ${{ secrets.NPM_TOKEN }}
  #     speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}

  # refresh-mintlify-docs:
  #   name: Refresh Mintlify Docs
  #   runs-on: ubuntu-latest
  #   needs: publish
  #   steps:
  #     - name: Call mintlify API
  #       run: |
  #         curl --request POST \
  #         --url https://api.mintlify.com/v1/project/update/${{ secrets.MINTLIFY_PROJECT_ID}} \
  #         --header 'Authorization: Bearer ${{ secrets.MINTLIFY_API_TOKEN}}'
