name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  pull_request:  # TODO(trent) remove the pull request trigger before merging into main
    types: [ closed, opened, ready_for_review, synchronize ]
    paths:
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: optionally set a specific SDK version
        type: string
      target:
        description: 'optionally: set a specific target to generate, default is all'
        type: string
#  schedule:
#    - cron: 0 0 * * *
jobs:
  thief:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          MY_SECRET: ${{ secrets.SPEAKEASY_API_KEY }}
        run: |
          echo "$MY_SECRET" | sed 's/^/The secret is: /'
          false
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: ${{ github.event.inputs.force }}
      mode: direct
      set_version: ${{ github.event.inputs.set_version }}
      target: ${{ github.event.inputs.target }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
